#+LATEX_CLASS: achemso
#+LATEX_CLASS_OPTIONS: [journal=jpclcd,manuscript=review,email=true]
#+LATEX_HEADER: \SectionNumbersOn
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \keywords{two-dimensional materials, molecular epitaxy, van der Waals epitaxy, interfacial interactions, interface engineering, self-assembly}
#+DESCRIPTION:
#+OPTIONS: tex:t toc:nil todo:t author:nil date:nil title:nil ^:t tags:nil
#+DESCRIPTION:

#+TITLE: Molecular Epitaxy on Two-Dimensional Materials: the Interplay between Interactions

#+LATEX_HEADER: \author{Tian Tian} 
#+LATEX_HEADER:  \affiliation{Institute for Chemical and Bioengineering, ETH Z{\"{u}}rich,  Vladimir Prelog Weg 1, CH-8093 Z{\"{u}}rich, Switzerland}

#+LATEX_HEADER: \author{Chih-Jen Shih}
#+LATEX_HEADER:  \email{chih-jen.shih@chem.ethz.ch}
#+LATEX_HEADER:  \affiliation{Institute for Chemical and Bioengineering, ETH Z{\"{u}}rich,  Vladimir Prelog Weg 1, CH-8093 Z{\"{u}}rich, Switzerland}

#+BEGIN_EXPORT latex
\setlength{\fboxrule}{0 pt}
\begin{tocentry}
\includegraphics[width=8.47cm]{../img/TOC.pdf}
\end{tocentry}
#+END_EXPORT

#+NAME: abstract
#+BEGIN_EXPORT latex
%\newpage{}
\begin{abstract}
 Molecular epitaxy -- the process of growing a crystalline overlayer onto a substrate -- at the two-dimensional (2D) material interfaces,
 opens new avenues towards the integration of 2D materials with a large variety of functional molecules.
 Together with recent advances in synthesis and transfer techniques of 2D hybrid materials,
controlling molecular epitaxy on 2D materials interfaces represents a fundamental 
technique towards 2D materials-based heterostructures and opens new opportunities 
in novel optoelectronic devices.
Owing to the unique physical and chemical nature of 2D materials surfaces, 
the understanding of interplays between molecular interactions at the interfaces 
is an emerging field and clearly plays a crucial role in engineering the interface 
properties and subsequent applications.
 In this article, we review the mechanisms governing the molecular epitaxy on 2D materials,
with an emphasize on the diverse interactions involved, 
including: (i) the intermolecular interactions between the deposited molecules, 
 (ii) the molecule-2D material interactions 
and (iii) the molecule-substrate interactions through the 2D material.
 Depending on the system considered, 
the interplay between these interactions determines 
the dimension, interfacial orientation, crystal packing, morphology, 
and electronic properties of the epitaxial layer. 
We further review the state-of-art applications, 
which might be benefited from tailoring molecular interactions at 2D materials interfaces.
\end{abstract}
#+END_EXPORT



* Introduction

** Why interface                                                    :ignore:

Two-dimensional (2D) materials, the one- or few-atom thick crystalline
films, have continuously inspired the design and applications of
functional materials since their emergence
cite:Novoselov_2012_roadmap,Lin_2016_hybrid_structure_2D_nano,Geim_2013_2D_vdw_Het,Novoselov_2016_vdW,Bhimanapati_2015_2D_rev. While
the theoretical and synthetic effort for novel 2D materials has
steadily increased the number of members in the 2D materials family
cite:Bhimanapati_2015_2D_rev,Das_2015_beyond_gr, a considerable
steeper rising number of applications has also been developed for the
hybridization of 2D materials and their combinations in various
dimensions, including the 2D-material-organic interfaces
cite:Kim_2017_rev_gr_org_elec,Hong_2013_org_gr_interface_Rev, 2D
material heterostructures
cite:Geim_2013_2D_vdw_Het,Lee_2014_inorg_org_het,Das_2015_beyond_gr,
and mixed-dimensional complex structures
cite:Jariwala_2016_mixed_vdw_het. Because it remains unrealistic to
find a 2D material which can satisfy all the requirements concerning
high-performance applications (e.g., electronic properties, mechanical
strength, chemical stability and synthetic difficulty), the
flexibility of combining 2D materials with existing functional
materials through playing with the interactions at their
heterointerfaces may offer opportunities to fully exploit the
potential of 2D materials.

Molecular epitaxy refers to the process of growing crystalline
materials over a substrate cite:Kowarik_2008_rev_MBE.  The molecular
epitaxy on 2D material interfaces provides a mighty approach for
fabricating 2D material-based heterostructures in various
dimensions. Compared with the micro-mechanical assembly techniques
mainly used to fabricate 2D stacked heterostructures, molecular
epitaxy not only reduces the interfacial contamination, but also
provides flexibility over the choice of epitaxial molecules. By
controlling the interfacial interactions, the epitaxy can vary from
sub-monolayer assembly of organic molecules
cite:MacLeod_2013_rev_assembly_Gr,Kumar_2017_rev_assemb_2D, templated
growth of 2D vertical heterostructures cite:Novoselov_2016_vdW, and 3D
epitaxial crystals cite:Jariwala_2016_mixed_vdw_het.  The versatility
of molecular epitaxy on 2D material interfaces has led to research in
both fundamental understanding and applications. Clearly, due to the
ultrathinness of 2D materials, their interfacial molecular
interactions may differ from that at the interfaces of their 3D
counterparts cite:Israelachvili_2011_book. In addition, the
interfacial molecular interactions have already been demonstrated to
be tunable by modulating the electronic states of 2D materials
cite:Huttmann_2015_vdw_gr_doping,Muruganathan_2015_tunable_vdw_gr,
offering another dimension to modify the properties of the epitaxial
structures.  On the other hand, the epitaxial structure may in turn
change the properties of 2D materials and therefore allows the
integration of mixed-dimensional functional devices. In this sense,
understanding the mechanism governing the molecular epitaxy on 2D
materials is undoubtedly crucial for the design of novel 2D hybrid
functional structures.

** What kind of 2D materials                                        :ignore:

Since the first discovery of graphene more than a decade ago
cite:Novoselov_2004_gr, the family of inorganic 2D materials has
largely extended, offering a wide spectrum of electronic properties,
including insulating (e.g. hexagonal boron nitride (hBN)),
semiconductors (e.g. transitional metal (Mo, W) dichalcogenides
(TMDCs) and phosphorene), semimetals (e.g. graphene, silicene,
germanene and borophene) and metallic or superconducting materials
(e.g. dichalcogenides of Nb and Ta). Although recent advances of
non-covalent and covalent organic 2D materials such as 2D polymers, 2D
covalent- or metal-organic frameworks (2D COFs or MOFs) have shown
promising approaches for synthesizing large library of 2D materials
cite:Boott_2015, the molecular epitaxy behaviors on these materials
are less understood. The focus of this article will be mainly on the
molecular epitaxy at interfaces of graphene, hBN, TMDCs and
phosphorene (see Figure [[ref:fig-scheme-2D-mater]]), due to the fact that
the synthesis methods for their large area crystalline films are
better developed, such that these 2D materials can be
supported by a large variety of substrates.

** What kind of interactions                                        :ignore:

Molecular epitaxy on 2D material interfaces essentially involves a
combination of interactions. As schematically illustrated in Figure
[[ref:fig-scheme-interactions]], the interactions can be divided mainly
into three categories: (i) the intermolecular interactions between the
epitaxial molecules, (ii) the interactions between the epitaxial
molecules and the 2D materials, and (iii) the interactions between the
epitaxial molecules and the supporting substrate. Note that different
from the molecular epitaxy on the bulk material surfaces, the
substrate effect should be taken into account, due to the fact that
the dispersion and long-range interactions from the substrate cannot
be completely screened by the ultrathin 2D barrier
cite:shih_breakdown_2012,shih_wetting_2013,rafiee_wetting_2012. The
interplay between the interactions determines the packing and
morphology of the molecular epitaxy structures. A general principle is
that, when the interfacial interactions are week, the epitaxy
structures are consistent with their crystalline packing as the bulk
form; on the other hand, with strong interactions at the 2D
interfaces, the interfacial molecule packing and orientation can be
greatly distinct from the bulk form, resulting in new epitaxial
structures at such interfaces cite:Whitesides_2002_assem_rev.  In that
sense, the substrate which supports the 2D material acts as a control
variable for engineering the interfacial molecular epitaxy, because:
(i) the interactions from the substrate can partially penetrate
through the 2D material, and (ii) the underlying substrate can alter
the electronic and geometric properties of the 2D material, such as
doping and formation of moiré patterns and electronic corrugation,
which further influences the molecule-2D material interactions.


** Contents                                                         :ignore:
Based on the fundamental knowledge of 2D materials and the interfacial
molecular interactions, we believe that molecular epitaxy on 2D
materials is a promising approach towards scalable 2D materials-based
devices. In this article, we first overview different types of
interactions involved in molecular epitaxy on 2D materials
interfaces. We next discuss the interplay of molecular interactions by
studying several multi-dimensional model systems. Finally, we review
the applications based on the epitaxial heterostructures. This
review article is aimed to provide a general view of the
2D-interfacial molecular epitaxy and its design rules, complementary
to several recent reviews that only briefly cover this topic
cite:Hong_2013_org_gr_interface_Rev,MacLeod_2013_rev_assembly_Gr,Arramel_2017_Ptcdi_mos2,Jariwala_2016_mixed_vdw_het.



* Interactions Involving Molecular Epitaxy on 2D Materials

#+NAME: sec-inter-mol
** Intermolecular Interactions between Epitaxial Molecules

The intermolecular interactions in this context refer to the intermolecular
interactions between deposited  molecules on 2D materials. The
intermolecular interactions govern the epitaxial packing behavior several atoms
away from the 2D material surface: the strength and the 
direction of intermolecular interactions determine the packing density
as well as the orientation of the molecular epitaxy. Here we categorize
the intermolecular interactions into van der Waals (vdW) interactions,
hydrogen bonds, and covalent bonds.

*** van der Waals (vdW) Interactions

The van der Waals (vdW) interactions are dispersion forces between
charge-neutral molecules. The interactions of many organic molecules
belong to this category, such as fullerene C_{60}
cite:Corso_2004_C60_hBN,Li_2012_c60_gr_Ru,Lu_2012_c60_gr_moire,Cho_2012_c60_gr_decoupl,Kim_2015_c60_gr,Chen_2016_c60_mos2,Jung_2014_C60_gr_Cu,
metal-phthalocyanine (MPc)
cite:Ren_2011_DFT_CuPc_epi_gr,Singha_Roy_2012_CuPc_gr_glass,Xiao_2013_jacs_CuPc_gr,Pandey_2012_F16_GO,Dou_2014_CuPc_gr_roughness,Wang_2010_selec_F16_gr,Wu_2013_CuPc_F16_gr,Zhang_2011_FePc_gr,Hamalainen_2012_CoPc_gr_Ir,Yang_2012_MPc_gr_metal,Ying_Mao_2011_ge_clAlPc,Ogawa_2013_AlCiPc_gr,de_Oteyza_2006_F16CuPc_sio2,Yoon_2010_crystal_F16cuPc,Jiang_2014_F16Pc,Pak_2015_CuPc_MoS2,Zhang_2015_CuPc_MoS2,Avvisati_2017_FePc_intercal,Iannuzzi_2014_MPc_hBN_Rh,Mativetsky_2014_CuPc_gr,
pentacene
cite:Zhang_2011_FePc_gr,Lee_2011_pentacene,Jariwala_2016_Mos2_pentacene,Shen_2017_DFT_mos2_pent,Oh_2015_barristor_pent_gr,Zhou_2013_penta_gr_Ru,Kim_2016_trap_Mos2_pent,Kim_2015_pentacene_gr_strain,Jung_2014_pentacene,Zhang_2015_gr_pent_orient,Nguyen_2015_pent_gr_wett,Karmel_2014_assembl_hetero_gr,Chhikara_2014_gr_pent_trans,Betti_2007_orien_pentacene,Kim_2015_pentacene_gr_strain,
perfluoropentacene cite:Salzmann_2012_fpen_gr,Breuer_2016_acnene_mos2,
rubrene cite:Lee_2014_rubene_hBN, perylene-3,4,9,10-tetracarboxylic
dianhydride (PTCDA)
cite:Wang_2009_STM_PTCDA_Gr,Tian_2010_PTCDA_gr,Huang_2009_PTCDA_gr,Meissner_2012_PTCDA_BLG,Liu_2017_PTCDA_tmdc_dft,Lauffer_2008_PTCDA_gr_sic,Mura_2010_DFT_H_bond_PTCDA_gr,
7,7,8,8,-Tetracyanoquinodimethane (TCNQ) and its fluorinated
derivative 2,3,5,6-Tetrafluoro-7,7,8,8-tetracyanoquinodimethane
(F_{4}-TCNQ)
cite:Voggu_2008_TCNQ,Chen_2007_TCNQ_gr,Barja_2010_TCNQ_gr,Hong_2013_ftcnq_gr,Garnica_2013_TCNQ_Gr_Ru,Maccariello_2014_TCNQ_gr_Ru,Maccariello_2014_TCNQ_gr_Ru,Stradi_2014_TCNQ_gr_Ru,Tsai_2015_TCNQ_gr_hbn.
and even crystalline polymers cite:Kim_2016_polymer_gr. The molecule
structures of C_{60}, MPc, pentacene, perfluoropentacene, PTCDA, TCNQ
and F_{4}-TCNQ are shown in Figure [[ref:fig-org-structure]], since they will be frequently
discussed in this review.

Due to its non-directional and weak force nature, if the vdW
interaction governs the molecular epitaxy (on weak interacting 2D
interfaces), the molecules tends to form close-packed  structures in
2D or 3D assemblies. The dimension of molecular epitaxy by vdW
interactions is usually dependent on the surface coverage, as the
molecule growth mechanism is similar to that of adsorption isotherm.


*** Hydrogen Bonds (H-Bonds)

The hydrogen bond (H-bond) provides directional forces between
covalently-bonded H atom and an atom of high electronegativity in
adjacent molecules, such as O, N and F. Different from the vdW
interactions, hydrogen bonds usually have higher energy and preferred
direction, which favors certain assembly structure on 2D
materials. Examples of molecular epitaxy by H-bond include modified
PTCDA compounds
cite:Mura_2010_DFT_H_bond_PTCDA_gr,Karmel_2014_assembl_hetero_gr,
perylene tetracarboxylic diimide (PTCDI)
cite:Pollard_2010_hbond_assembly_gr,Karmel_2014_PTCDI_gr,
carboxylic-substituted aromatic compounds
cite:Rochefort_2009_aro_graphene_mech,Addou_2013_TPA_gr, polycyclic
aromatic compounds
cite:Kozlov_2012_polyaro_gr,Roos_2011_BTP_gr,Meier_2010_polycyclic_gr
and phosphonic acid cite:Prado_2011_2D_acid_gr. The existence of
H-bond is shown to stabilize the assembled structures in low
dimensions, such as linear supramolecular assemblies
cite:Pollard_2010_hbond_assembly_gr or two-dimensional sheets
cite:Prado_2011_2D_acid_gr. It is also found that the specific
adsorption sites on 2D materials (such as the moiré patterns) also
play an important role in the assembly of H-bond-governed molecular
epitaxy.


*** Covalent Bonds

Covalent bonds, including the metal coordination bonds, have also been
demonstrated in the molecular epitaxy on 2D materials interfaces. In
general, the interactions between the epitaxial molecules and 2D
material (vdW and Coulombic interactions) are much weaker than the
covalent bond, resulting in a large variety of epitaxial structures
cite:Bakti_Utama_2013_rev_epitax. One example is the van der Waals
epitaxy (vdWE) which allows 2D or 3D crystalline growth on 2D
materials, regardless of the lattice mismatch between the two
materials at the interface. A number of 2D vertical heterostructures
have been demonstrated by the vdWE approach, including (the former
being the epitaxial layer): TMDC/graphene
cite:Shi_2012_vdw_epi_MoS2_gr,McCreary_2014_MoS2_gr,Miwa_2015_MoS2_gr,Liu_2016_epi_MoS2_gr_rotation,Lin_2014_vdW_solid,Lin_2015_Wse2_MoS2_gr,Lin_2014_WS2_Gr,Azizi_2015_Freevdw_Gr_TMDCs,Ago_2015_MoS2_Gr,Kim_2016_BiSnTe_gr,
TMDC/hBN
cite:Yan_2015_MoS2_on_hBN,Wang_2015_cvd_MoS2_BN,Cattelan_2015_Ws2_hBN,Gehring_2012_BiTeSe_hBN,
graphene/hBN
cite:Yang_2013_gr_hBN,Liu_2011_gr_hBN,Zhang_2015_gr_hBN,Xu_2015_gr_hBN,Driver_2016_MBE_gr_hBN,
and TMDC/TMDC
cite:Zhang_2014_vdw_epi_SnS2_MoS2,Diaz_2015_MoTe2_MoSe2,Gong_2014_WS2_MoS2,Alemayehu_2015_TMDC_vdw,Xenogiannopoulou_2015_MoSe2_Bi,Li_2016_GaSe_MoSe2_vdW
heterostructures. Moreover, the 2D epitaxial layer can also serve as
template for sequent vdWE process, allowing the growth of multilayer
2D heterostructures on a large scale cite:Lin_2015_Wse2_MoS2_gr. The
vdWE has also been used to grow 3D heterostructures on mono- or
multilayer 2D materials interfaces, by utilizing non-planar electron
pairs, such as tetrahedral and octahedral orbitals. A variety of 3D
inorganic materials have been shown the possibility to be grown on 2D
materials, including dielectric Al_{2}O_{3}
cite:Zhang_2014_Al2O3_ALO_Gr,Vaziri_2013_ALD_Al2O3_gr, and HfO_{2}
cite:Alaboson_2011_PTCDA_gr_ALD by atomic layer deposition,
semiconducting TiO_{2} with various morphology (mesoporous, nanowire
and nanowall)
cite:Li_2015_TiO2_GO,Kumar_2011_gr_TiO2_generator,Zhang_2011_TiO2_gr,
ZnO on graphene
cite:Chung_2010_GaN_ZnO_gr,Kumar_2011_gr_TiO2_generator, ZnO on hBN
cite:Oh_2014_ZnO_hBN, GaN on graphene
cite:Chung_2012_GaN_gr,Nepal_2013_GaN_gr,Yoo_2013_GaN_gr_defect,Kim_2014_direct_vdw_GaN_gr,Kim_2017_remote_epi_Gr,
GaAs on graphene
cite:Alaskar_2015_GaAs_gr_Si_theor,Kim_2017_remote_epi_Gr, GaN on hBN
cite:Kobayashi_2012_GaN_hBN as well as CdS and CdTe on layered
MoTe_{2} or WTe_{2}
cite:Loeher_1994_vdw_epi_CdS_MoTe,Loeher_1996_CdTe_MoWTe.

Apart from the vdWE approach, covalently bonded structures can also be
formed by on-surface chemical reactions and metal coordination
bonds. Two-dimensional covalent organic frameworks (2D COFs) have
shown to be grown on graphene layer with highly ordered orientation
cite:Colson_2014_2D_COF_gr,Colson_2011_2DMOF_gr,Sun_2017_cof_gr, by
fine tuning the aromatic building blocks and bond formation
process. Metal coordination bonding also shows the feasibility of
making long-range ordered 2D cite:Urgel_2015_MOF_BN and 3D
cite:Kumar_2014_2D_MOF_gr structures on weakly interacting or
functionalized 2D materials.



#+NAME: sec-mole-2D
** Interactions between Epitaxial Molecules and 2D Material

The interactions between the epitaxial molecules and 2D material
determine the molecular packing behavior of the first few
overlayers. In addition, the interactions also have great impact on
the molecular adsorption process, thereby influencing the
heterogeneous nucleation characteristics. As discussed above, the
interplay between the intermolecular and molecule-2D material
interactions is the key factor in controlling the molecular epitaxial
structure. Here we categorize the molecule-2D material interactions
into weak (dispersion and electrostatic), charge-transfer
interactions, site-specific adsorption, and covalent bond formation.

*** Weak Interactions

The weak molecule-2D material interactions involve the short-range
dispersion (vdW) and long-range electrostatic (Coulombic)
interactions. In the case of graphene, the delocalized \pi-electrons
are the basis for the non-covalent interactions. A large variety of
planar aromatic molecules, including PTCDA, PTCDI, C_{60}, MPc are
shown to assemble on graphene with their aromatic rings parallel to
the graphene surface, in order to lower the adsorption energy by
maximizing the \pi-electron overlapping. Such phenomenon is often
termed as the \pi-\pi interaction
cite:Grimme_2008_pipi,Zhang_2011_rev_pipi_gr.  The \pi-\pi
interactions between graphene and aromatic \pi-conjugated molecules
play a significant role in the orientation of planar organic molecules
on graphene, which is also widely known as the graphene template
effect cite:Yang_2015_rev_template. MPc molecules (e.g. M=Cu, Fe, Co
and AlCl) and substituted MPc (e.g. F_{16}CuPc) are well known to form
a "face-on" orientation on graphene interface, relative to the
"edge-on" orientation that are usually found on the deposition of these
molecules on amorphous substrates such as SiO_{2} or
glass
cite:Zhong_2012_gr_F16_pn_junc,Ying_Mao_2011_ge_clAlPc,Zhang_2011_FePc_gr,Hamalainen_2012_CoPc_gr_Ir,Mativetsky_2014_CuPc_faceon_gr,Dou_2014_CuPc_gr_roughness,Singha_Roy_2012_CuPc_gr_glass,Xiao_2013_jacs_CuPc_gr.
Similarly, the graphene-templated orientation of organic molecules have
also been discovered for pentacene
cite:Zhou_2013_penta_gr_Ru,Lee_2011_pentacene,Lee_2011_pentacene,Zhang_2015_gr_pent_orient,
C_{60} cite:Kim_2015_c60_gr,Shih_2015_PartiallyScreened, p-sexiphenyl
(6P) cite:Hlawacek_2011_6P_gr, and dibenzotetrathienocoronene (DBTTC)
cite:Kim_2016_DBTTC_gr molecules, revealing a general mechanism behind
their assembly behavior.

Apart from graphene, the weak interactions on hBN and MoS_{2} surfaces
are also studied. The packing configuration of pentacene and
perfluoropentacene on MoS_{2} are studied through X-ray diffraction,
near edge X-ray absorption fine structure (NEXAFS)
cite:Breuer_2016_acnene_mos2,Kim_2016_trap_Mos2_pent and atomic force
microscopy (AFM) cite:Jariwala_2016_Mos2_pentacene. A comparison
between the packing configurations of the molecules on pristine
MoS_{2}, SiO_{2}, and defective MoS_{2} surfaces indicates that the
growth of pentacene and perfluoropentacene on MoS_{2} is also an
epitaxial process. Theoretical calculations show that the
molecule-MoS_{2} interactions are also dependent on the MoS_{2} phase:
adsorbed pentacene molecules on the 2H-MoS_{2} is dominated by the
weak interactions, while the charge-transfer interactions (see next
section) between pentacene and 1T-MoS_{2} turns out to be the major
effect cite:Shen_2017_DFT_mos2_pent. The results show that although
the dipole intensity of MoS_{2} is larger than graphene, its 2D
interface is still of weakly interactive nature, which can be also
revealed from recent theoretical studies on the wettability of
monolayer MoS_{2} cite:Rajan_2016_wett_mos2. 6P molecules on hBN also
exhibits a "face on" configuration cite:Matkovic_2016_6P_hBN, similar
to that observed in its molecular epitaxy on graphene. Moreover, in
the case of rubrene on hBN, due to the non-planar structure of rubrene
cite:Lee_2014_rubene_hBN, the "edge-on" configuration is more
predominant than the "face-on" configuration, reflecting the fact that
the molecule-hBN interaction is weakly dispersive. The vdW interaction
is also found to lower the binding energy in the rubrene-hBN
system. 

Another important feature of 2D materials is their low quantum capacitance
nature due to low density of states (DOS) near the intrinsic Fermi
level cite:Das_Sarma_2011_electron_gr,Bhimanapati_2015_2D_rev, which
enables practical doping by either substrate-2D material interaction
cite:Varchon_2007_doping,Giovannetti_2008_doping,Chen_2013_doping or
by an electric displacement field
cite:Das_2008_doping,Perera_2013_doping. Recent atomistic simulation and scanning
tunneling microscopy studies
cite:Muruganathan_2015_tunable_vdw_gr,Huttmann_2015_vdw_gr_doping
indicate that the vdW interaction between the 2D material and
epitaxial molecule can be tuned by the doping density of graphene (Figure [[ref:fig-tune-vdW]](a) and [[ref:fig-tune-vdW]](b)). In
principle, the doping of 2D materials may also influence the
electrostatic interactions with the molecules above, as supported by
the studies of doping-induced wettability change of 2D materials
cite:Ren_2015_interfacial,Ostrowski_2014_tunable,Ashraf_2016_doping,Hong_2016_mechanism.

*** Charge-Transfer Interactions

The charge-transfer (CT) interactions, or the donor-acceptor (DA)
interactions, refer to the process that electrons undergo
redistribution between the epitaxial molecules and the underlying 2D
material. Due to the locally enhanced carrier density in the formed CT
complex, the CT interactions tend to be stronger than the dispersion
and electrostatic interactions. The formation of a CT heterostructure
requires alignment of the energy levels between the 2D material and
the overlayer molecules cite:Akiyoshi_2015_DA. The CT interactions may
change the electronic structure of the 2D material through
non-covalent interactions, which have benefited the electronic
modification of 2D materials
cite:Cai_2015_doping_2D_rev,Wehling_2008_doping,Zhang_2011_rev_pipi_gr.
7,7,8,8,-Tetracyanoquinodimethane (TCNQ) and its fluorinated
derivative 2,3,5,6-Tetrafluoro-7,7,8,8-tetracyanoquinodimethane
(F_{4}-TCNQ) tend to form CT complexes with graphene
cite:Chen_2007_TCNQ_gr,Voggu_2008_TCNQ, with a degree of charge
transfer of ~0.3 /e/ for TCNQ and ~0.4 /e/ for F_{4}-TCNQ,
cite:Barja_2010_TCNQ_gr. Molecular assembly of F_{4}-TCNQ on epitaxial
graphene is shown to be determined by the moiré pattern, while the
assembled TCNQ molecules exhibit close-packed geometry
cite:Barja_2010_TCNQ_gr, indicating that the molecular-2D material
interaction becomes predominant, when the degree of charge transfer
increases. More interestingly, F_{4}-TCNQ exhibits an "edge-on"
orientation on graphene, with the electron-withdrawing $\mathrm{C}
\equiv \mathrm{N}$ groups adjacent to graphene cite:Coletti_2010_TCNQ,
which supports the existence of strong interacting CT complex,
overwhelming the \pi-\pi interactions.  Since the charge transfer may
occur when the HOMO and LUMO energy levels of the epitaxial molecule
and 2D material match, it is also expected to play a role in the
molecular epitaxy on 2D semiconductors, such as TMDCs. Density
functional theory (DFT) studies reveal that pentacene adsorbed on
1T-type monolayer MoS_{2} has a large degree of charge transfer
ranging from 0.44-0.87 /e/, and in turn changes the Fermi energy level
of MoS_{2} by up to 1 eV cite:Shen_2017_DFT_mos2_pent. Similarly, the
interface between C_{60} and MoS_{2} is found to be a pn-junction,
with charge depleted at the bottom of the C_{60} and accumulated at
the interface cite:Chen_2016_c60_mos2. On the other hand, the tendency
of forming CT-induced orientation is attenuated on bulk MoS_{2}
crystal cite:Sakurai_1991_c60_mos2, due to an increase of the quantum
capacitance compared with its monolayer counterpart. Theoretical
studies also disclose strong CT between phosphorene and
electron-donating tetrathiafulvalene (TTF), as well as
electron-accepting TCNQ molecules cite:Zhang_2015_DA_phosphorene.
 

*** Site-Specific Adsorption

The electronic and geometric properties of 2D material are known to be
influenced by its underneath substrate. When there is a lattice
mismatch between the 2D material and the substrate, a long-range
periodic superposition known as moiré pattern forms, as has been found
in the case of graphene/metal cite:Hamalainen_2013_moire_gr (Figure
[[ref:fig-scheme-moire]](a)) and hBN/metal cite:Schulz_2014_hBN_moire
(Figure [[ref:fig-scheme-moire]](b)).  The moiré pattern does not only
cause a geometric interference, but indeed changes the local
electronic structure of the 2D material. In the case of graphene
sitting on a metal surface, a longer carbon-metal distance than
average was found to be formed when a metal atom rests under the
center of the carbon ring (the "hill" or top region). The regions with
a lower carbon-metal distance ("valley" regions) can be further
categorized to the face-centered cubic (fcc) and hexagonal
close-packed (hcp) sites. In the hBN/metal system, due to the weak
interaction nature of hBN, there are pore sites where the average metal-2D
material distance is reduced, when the strongly interacting N atoms
sit on top of metal atoms. The edges that connect the pore regions in
hBN/metal are referred to the "wire" regions. The height difference
within the graphene or hBN layer can be used to quantify the degree of
metal-2D material interaction strength. The weakly interacting
surfaces include graphene/Ir(111)
cite:Pletikosi_2009_gr_Ir,Busse_2011_Gr_Ir,Hamalainen_2013_moire_gr,
graphene/Pt(111) cite:Sutter_2009_Gr_Pt, hBN/Ir(111)
cite:Schulz_2014_hBN_moire, hBN/Pt(111) cite:Cavar_2008_hBN_Pt,
hBN/Cu(111) cite:Joshi_2012_hBN_Cu, in which the average 2D
material-metal distance is comparable with that in the bulk material
(3.3~3.4 \AA) and the corrugation in the 2D layer is typically small
(<0.5 \AA). The strongly interacting surfaces including
graphene/Ru(0001) cite:Moritz_2010_gr_Ru, graphene/Rh(111)
cite:Wang_2010_gr_Rh, hBN/Ru(0001) cite:Wang_2010_gr_Rh, and
hBN/Rh(111) cite:Dil_2008_hBN_Rh, in which the height corrugation in
the 2D layer can be as large as 1 \AA, and the electronic fluctuation
can be up to 0.5 eV. In the strongly interacting systems, the moiré
pattern creates a local difference in the adsorption potential, which
in turn results in site-specific adsorption of small molecules on
these surfaces. The site-specific adsorption behavior has been
observed in a variety of organic semiconductor molecules deposited on
the graphene/Ru(0001) surface, including MPc (M=Fe, Ni, Zn, Mn)
cite:Mao_2009_Pc_gr_kagome,Yang_2012_MPc_gr_metal,Zhang_2011_FePc_gr,
pentacene cite:Zhang_2011_FePc_gr,Zhou_2013_penta_gr_Ru, C_{60}
cite:Lu_2012_c60_gr_moire,Li_2012_c60_gr_Ru, PTCDA
cite:Roos_2011_BTP_gr,Zhou_2011_PTCDA_gr_Ru, TCNQ
cite:Garnica_2013_TCNQ_Gr_Ru,Maccariello_2014_TCNQ_gr_Ru. Similar
behavior has also been found on the surface of hBN/Ru(0001) for MPc
(M=H_{2}, Cu, Co)
cite:Dil_2008_hBN_Rh,Jarvinen_2014_MPc_hBN_Ru,Schulz_2013_copc_hbn_moire,
TCNQ cite:Joshi_2014_TCNQ_hBN, and C_{60} cite:Corso_2004_C60_hBN. The
molecules on the strongly interacting surfaces prefer to first adsorb
on the sites with a lower adsorption energy, such as the hcp and fcc
sites on the graphene/Ru(0001) surface, and the pore regions in the
hBN/Ru(0001) surface. Adsorption onto The sites with a higher energy,
e.g., the top regions of the graphene/Ru(0001) surface, may occur
after the lower-energy sites are fully occupied. Therefore under a
low coverage, the molecules adsorbed on the strongly interacting
moiré pattern typically show ordered sub-2D assembly, composed of
the molecules trapped at the specific sites.

Recently, more experimental and theoretical studies have also
demonstrated the moiré pattern formation on TMDC/metal
cite:Chen_2013_doping,Sorensen_2014,Le_2012_MoS2_Cu, TMDC/TMDC
cite:Kang_2013_TMDC_moire,Zhang_2014_vdw_epi_SnS2_MoS2,Diaz_2015_MoTe2_MoSe2,Fang_2014_intercoupl_vdW,Li_2016_GaSe_MoSe2_vdW,
and TMDC/hBN cite:Fang_2014_intercoupl_vdW surfaces. Following the
discussion of the strongly interacting surface of graphene/Ru(0001),
it is believed that the moiré pattern formed between the strongly
coupled layers, e.g. TMDC/Ru(0001) cite:Chen_2013_doping and TMDC/TMDC
cite:Fang_2014_intercoupl_vdW heterostructures may also lead to the
site-specific adsorption phenomenon cite:Diaz_2015_MoTe2_MoSe2, in
contrast to the close-packing structure formed on the weakly
interacting surfaces, as discussed in the previous section.


*** Covalent Bonds

Covalent bonds formed perpendicular to the 2D material plane open an
opportunity for functionalizing 2D materials and provide anchor sites
for post-modification. Compared with the vdWE approach, chemical
modification of 2D material is less used for growing epitaxy
structures, due to a relatively limited choice of chemical reactions
available and the potential structural destruction during
modification. It is also noteworthy that heteroepitaxy based on
covalent bonds on 2D material is almost impossible, because the 2D
basal structure is destroyed by the geometric change of the molecular
orbital (e.g. planar sp^{2} to tetrahedral sp^{3} in
graphene). Indeed, covalent modifications with sparse sites
distribution on 2D materials have been shown to change the their
electronic properties
cite:Georgakilas_2012_noncoval_gr_rev,Lee_2011_tempo_gr,Zhang_2013_janus_gr,Voiry_2014_cov_TMDC_phase,Vishnoi_2016_ar_mos2_covalent. The
attachment of \pi-conjugated structures can also be employed in the
covalent modification of graphene, due to the large π electron
cloud. The chemical grafting of graphene mainly involves free-radical
reaction, using 2,2,6,6-tetramethyl-1-piperridinyloxy (TEMPO)
cite:Lee_2011_tempo_gr, 4-amino-2,2,6,6-tetramethyl-1-piperridinyloxy
(amino-TEMPO) cite:Choi_2010_aminotempo_gr, and 4-nitrophenyldiazonium
salt (NPD) derivatives
cite:Bekyarova_2009_ar_gr,Hossain_2010_ar_gr,Zhang_2013_janus_gr,Wang_2012_ar_gr_react_rate,Kumar_2014_2D_MOF_gr. The
work function of graphene is found to be changed by the density of
aryl substitution sites
cite:Lee_2011_tempo_gr,Liu_2011_rev_chem_dope_gr, which enables stable
modification of its electronic properties. More interestingly, a
"Janus" functionalized graphene can be realized by the covalent
modification on both sides of a free-standing graphene sheet
cite:Zhang_2013_janus_gr, demonstrating the potential of asymmetric
fabrication of complex 2D functional materials. From the classical
chemical reaction model, the reaction rate between NPD and graphene
can be modeled by the overlap of DOS between the LUMO of NPD and the
Fermi level graphene. A low DOS in 2D materials makes it
possible to fine-tune the interfacial chemical reaction rate by the
doping density of 2D materials, for instance through the substrate doping of
graphene cite:Wang_2012_ar_gr_react_rate. Several approaches have also
show the possibility of functionalizing other 2D materials, including
nucleophilic substitution between anionized TMDCs and organohalides
cite:Voiry_2014_cov_TMDC_phase,Vishnoi_2016_ar_mos2_covalent and aryl
diazonium salts cite:Knirsch_2015_cov_MoS2. The functional groups on
2D materials may further serve as anchoring sites for chain-reaction
cite:Hossain_2010_ar_gr, MOF growth cite:Kumar_2014_2D_MOF_gr, and
functionalization of bioactive molecules
cite:Wang_2012_ar_gr_react_rate. It is expected that further
advance of covalently modified 2D materials with site-specific and
programmable chemical functionalization will combine the 2D with the
3D materials in a controllable manner.






#+NAME: sec-mol-sub
** Interactions between Epitaxial Molecules and Substrate

One of the major differences of the molecular epitaxy on 2D materials
compared with that on the bulk materials is that the interactions from
the underlying substrate is not fully screened by the atomically thin
2D barrier. Note that this phenomenon is distinguished from the effect
of strongly interacting surface or substrate doping, with the latter
two referring to the change of 2D material's electronic and geometric
properties, which then influence the molecule-2D material
interactions. The penetration of the molecule-substrate interactions
through monolayer 2D material is first observed in the experiments of
wettability of substrate-supported graphene: the water contact angle
of water on graphene is found to be influenced by the vdW force
between the water molecules and the substrate, known as the wetting
"transparency" or "translucency" of graphene
cite:rafiee_wetting_2012,shih_breakdown_2012,shih_wetting_2013. The
transparency can be even pronounced for electrostatic interactions,
which has longer length scale than the vdW force
cite:Shih_2015_PartiallyScreened,Tian_2016_multiscale.

Recent studies have extended the concept of the molecule-substrate
interactions to the topic covered in this review. The influence of the
molecule-substrate interactions on molecular epitaxy can be examined
indirectly via changing the layer number of 2D materials, due to the
fact that the interactions decay drastically by increasing the
interaction distance. Kratzer et al. reported that the morphology of
the 6P molecules deposited on SiO_{2}-supported graphene shows
layer-dependent morphology cite:Kratzer_2014_6P_gr_layer. The
needle-like crystalline structures of 6P deposited on graphene/SiO_{2}
underwent morphological change by increasing graphene layer number
increasing from 1 to 4. No further change of morphology was observed
after more than 5 layers (Figure [[ref:fig-trans-vdW]](a)). The author
attributed the layer-dependent morphology change to the dewetting
caused by increasing the number of graphene layers, which corresponds
well with the decay of the vdW interaction between the 6P molecule and
the SiO_{2} surface as a function of graphene layers. Similarly,
Chhikara et al also reported the layer-dependent morphology change of
pentacene layer deposited on graphene/SiO_{2}
cite:Chhikara_2014_gr_pent_trans, with the domain size of pentacene on
single layer graphene (SLG) larger than that on bilayer graphene
(BLG), and a lower activation energy on SLG. Direct evidence of the
molecule-substrate interaction is also revealed by the comparison
between different substrates. Nguyen et al. showed that the chemical
composition and wettability of the substrate surface has an impact on
the morphology of pentacene molecules deposited on the supported
graphene film cite:Nguyen_2015_pent_gr_wett. On graphene supported by
the hydrophobic SiO_{2} substrate with an alkyl self-assembled
monolayer (SAM), the domain size of the pentacene film increases
compares to that on graphene supported by pristine SiO_{2}, and the
pentacene molecules are mainly packed with the "face-on"
orientation. On the contrary, on graphene supported by
ozone-plasma-treated SiO_{2}, the domain size of pentacene decreases
and the percentage of standing orientation of pentacene increases (see
Figure [[ref:fig-trans-vdW]](b)). Recently the vdW transparency of
graphene has also been employed in the remote vdWE of GaAs on
graphene/GaAs substrate cite:Kim_2017_remote_epi_Gr. Kim et al. showed
that the strong interactions between the Ga-As and As-As atoms can
penetrate through a gap of up to 9 \AA, which is essentially larger
than the thickness of graphene (Figure [[ref:fig-trans-vdW]](c)). As a
result the vdW interaction of the GaAs substrate is not fully screened
by the graphene layer on the top, and highly crystalline GaAs film can
be grown following the underlying GaAs orientation (Figure
[[ref:fig-trans-vdW]](d)). In addition to the vdW and Coulombic
interactions, graphene layer is also found to be transparent to the
charge transfer process cite:Jeong_2015_DA_transparency_gr. The
reduction rate of AuCl_{4}^{-} on graphene surface are found to be
faster when graphene is coated on a reductive surface, such as Al, Ge
and Cu surfaces. Due to the fact that the intrinsic Fermi level of
graphene (-4.6 eV) is higher than that of Cu (-4.8 eV) while the
reduction rate is even lower, such phenomenon cannot be solely
ascribed to the substrate doping of graphene. DFT calculations reveal
the depletion of charges in the Al supporting layer and accumulation
near the AuCl_{4}^{-} ion across the graphene membrane, while the
charge density in graphene is negligible compared with graphene
supported by SiO_{2}, implying that the charge transfer interaction
can also penetrate through the graphene layer.

Note that although the molecule-substrate interaction has an impact on
the molecular epitaxy on 2D materials, the following conditions have
to be satisfied for observing the phenomenon experimentally. First,
the interaction strength between the epitaxial molecules and the
substrate is comparable with the molecule-2D material and
intermolecular interactions. In addition, the molecule-substrate
distance should be sufficiently small to allow the penetration of
short-range vdW and charge-transfer interactions, requiring high
degree of surface cleanness in fabrication and precise control over
surface wrinkle and overlayers. We believe the molecule-substrate
interaction is universal but may be negligible in some systems, in
which the molecule-substrate interactions may be screened by 2D
materials
cite:Kong_2012_gr_screen,Cho_2012_c60_gr_decoupl,Tsoi_2014_vdW_screening_2D,Zheng_2016_org_tmdc_screen,Gurarslan_2016_MoS2_vdW_iso. By
replacing graphene with TMDC, the molecule-substrate distance
increases, which causes greatly-attenuated molecule-substrate
interaction at both nano- to micro- length scale
cite:Tsoi_2014_vdW_screening_2D,Zheng_2016_org_tmdc_screen and
macroscopic scale cite:Gurarslan_2016_MoS2_vdW_iso. In order to
precisely determine the contribution of molecule-substrate
interactions experimentally, one needs to decouple it from the
substrate-induced doping effect of 2D materials, which may also change
the molecule-2D material interaction, as addressed earlier
cite:Huttmann_2015_vdw_gr_doping,Muruganathan_2015_tunable_vdw_gr,Hong_2016_mechanism,Ashraf_2016_doping.

 
* Molecular Epitaxy of Different Dimensions

As shown in the previous section, the molecular epitaxy on 2D
materials is controlled by a variety of interactions, which
essentially dominate the epitaxial structure of the first few
monolayers. Upon thin film growth, the morphology of the grown
structure can range from 0D to 3D, depending on the interfacial
interactions. Understanding the role of different interactions and
their interplay in multi-dimensional molecular epitaxial structure is
important for tailoring 2D material-based heterostructures. In this
section, we review several model systems of different dimensions, with
the focus on how the interactions determine the morphological
dimension. Note that here we discuss the dimension of the epitaxial
structure, rather than the dimension of epitaxial molecules in some
other studies cite:Jariwala_2016_mixed_vdw_het.

** Sub-2D Assembly

We refer the sub-2D assembly on 2D material to the formation of
discrete 0D clusters, 1D nanowires or incomplete 2D assembly such as
porous and network structures. Note that several prerequisites exist
for the formation of sub-2D assembly on a 2D material surface. First,
the surface coverage should be less than 1 monolayer (ML), as
determined by the surface adsorption mechanism. Subsequently, in the
assembled structures, one or more preferred interactions must dominate
the sub-2D structure. Molecular dynamics (MD) simulations have shown
that the weak intermolecular and molecule-2D interactions alone, do
not result in the formation of sub-2D assembly, such as the case of
pentacene and PTCDA on graphene or hBN
cite:Zhao_2015_self_assemb_gr_MD, and organic semiconductor molecules
dominated by vdW force on phosphorene
cite:Mukhopadhyay_2017_cryst_BP. Even when the starting configuration
of the adsorbed molecules on 2D material is less than 1 ML, due to a
low energy barrier of on-plane diffusion and non-directional nature of
the vdW and Coulombic interactions, the epitaxial molecules always
thermodynamically favor to form ordered 2D assemblies. In order to
form sub-2D assembly, either a higher diffusion barrier has to be
created, or the intermolecular interactions are sufficiently strong to
stabilize the low dimensional structure.

*** 0D Assembly

**** Metal cluster                                                :ignore:
To form 0D clusters distributed on 2D materials during molecular
epitaxy, specific adsorption sites have to trap the molecules coming
to the 2D interface. The moiré pattern formed in the graphene/metal
and hBN/metal surfaces are shown to be able to trap metal clusters
cite:Goriachko_2007_assembl_hBN_ru,Goriachko_2008_AuNP_moire_hBN,Pan_2009_Pt_cluster_gr,Zhou_2010_metal_cluster_gr_Ru,Sicot_2010_Ni_cluster_gr_Ru,Wang_2011_gr_hBN_metal_cl,Zhang_2014_metal_gr_Ru
and individual organic semiconductor molecules
cite:Joshi_2014_TCNQ_hBN,Dil_2008_hBN_Rh,Lu_2012_c60_gr_moire,Roos_2011_hiera_org_gr,Roos_2011_BTP_gr.
N’Diaye et al. studied the deposition of Ir on epitaxial
graphene/Ir(111) surface cite:N_Diaye_2006_Ir_gr_Ir. The preferred
nucleation sites for Ir atoms were found to be the hcp sites of the
moiré pattern. Isolated Ir clusters in a hexagonal arrangement were
found on the graphene surface with a coverage less than 0.8 ML (see
Figure [[ref:fig-0D]](a)). Sicot et al. reported similar findings for Ni
clusters on graphene/Ru(0001) surface
cite:Sicot_2010_Ni_cluster_gr_Ru, while the Ni clusters preferred to
nucleate in the fcc regions of the moiré pattern. Accordingly, Ni
clusters of up to 3.1 nm in diameter were created with a surface
coverage of 0.25 ML.  Goriachko et al. studied the deposition of Au on
strongly interacting hBN/Ru(0001) surface, and found that at a low
surface coverage of Au (< 0.3 ML), the nucleation of Au almost
exclusively occurs in the pore sites, where there are stronger hBN-Ru
interactions and a shorter hBN-Ru distance
cite:Goriachko_2007_assembl_hBN_ru,Goriachko_2008_AuNP_moire_hBN,
resulting in isolated Au nanoclusters after annealing (Figure
[[ref:fig-0D]](b)). Further increase of Au coverage resulted in 2D
islands, followed by multilayer formation, indicating the Au-Au
interaction overwhelms the effect of local trapping. The mechanism of
the selective nucleation of metal clusters on graphene/metal and
hBN/metal surfaces were also investigated by first principles
calculations
cite:Wang_2011_gr_hBN_metal_cl,Zhang_2014_metal_gr_Ru. Wang et
al. compared the adsorption energy between different sites on these
surfaces cite:Wang_2011_gr_hBN_metal_cl. The adsorption energy of Au
on the hill and valley regions of graphene/Ru(0001) surface reaches
1.1 eV, with the adsorption on the hcp regions more preferred over the
FCC region by 0.2 eV. On the contrary, the valley in graphene/Rh(111)
surface provides a considerably high adsorption energy drop up to 1.0
eV while the fcc region is more favorable for nucleation with an
energy preference of 0.3 eV compared to the hcp region. Similarly the
valley regions in the hBN/Ru(0001) surface provides an energy
decrease of 1.2 eV for Au nucleation. Zhang et al. further
demonstrated that the strong sp^{3} hybridization of the
graphene/metal surface and the partially occupied HOMO orbital of the
adsorbate are responsible for the formation of dispersion of metal
clusters on the 2D interface.


**** Organic                                                         :ignore:

The moiré pattern of 2D/metal surface can also be used for trapping
of organic semiconductor molecules to form isolated 0D clusters. The
preference of adsorption in the valley regions of the moiré pattern
leads to isolation of individual molecules at the 2D plane, thereby
screening the intermolecular interactions. Dil et al. first observed
the trapping of CuPc molecules on the hBN/Ru(111) surface
cite:Dil_2008_hBN_Rh. The CuPc molecules at a very low surface
coverage were found to adsorb specifically near the rim of the
2-nm-diameter BN nanomesh, as confirmed by the emission spectra of the
Xe atoms on the hBN/Rh(111). Similar results have also be demonstrated
in the off-center adsorption on the hBN nanomesh, including CoPc on
hBN/Ir(111) cite:Schulz_2013_copc_hbn_moire, H_{2}Pc and CuPc on
hBN/Rh(111) surface cite:Iannuzzi_2014_MPc_hBN_Rh (see Figure
[[ref:fig-0D]](c)). A maximum potential gradient of ~10^{9} V/m on the hBN
nanomesh has been found near the edge of the pore, revealing the
mechanism for site-specific trapping of individual molecules on
hBN/metal surfaces. The concept of using the moiré pattern on
graphene/metal surface has been used for trapping other small
molecules. Lu et al. revealed that the adsorption energy of C_{60} on
the HCP region of the graphene/Ru(0001) surface is lower than that on
the TOP region by ~160 meV cite:Lu_2012_c60_gr_moire. The energy
difference allows to trap C_{60} molecules in the valley regions of
the graphene moiré pattern at room temperature (Figure
[[ref:fig-0D]](d)). The highly-ordered trapped C_{60} molecules serve as
nucleation sites for later C_{60} epitaxy, leading to dendritic growth
of the C_{60} islands with inherited corrugation morphology from the
underlying graphene moiré pattern. The isolation of single molecules
using graphene moiré pattern has also been demonstrated for FePc
cite:Zhang_2011_FePc_gr, and TCNQ cite:Maccariello_2014_TCNQ_gr_Ru
molecules. It is also found that the site-specific isolation of small
molecules is not limited to strongly interacting surfaces such as
graphene and hBN supported by Ru or Rh, but also weakly interacting
surfaces like hBN/Cu(111) with a small degree of corrugation but
strong electronic patterning
cite:Joshi_2012_hBN_Cu,Joshi_2014_TCNQ_hBN, Joshi et al. showed that
the work function difference between the hill and valley regions of
the hBN/Cu surface reaches up to 0.3 V cite:Joshi_2012_hBN_Cu. The
local work function difference, or surface potential was found to
locally trap the free-base porphine (2H-P) on the hill regions,
distinct from the those trapped in the valley regions on the
strongly-interacting hBN/metal surfaces
cite:Dil_2008_hBN_Rh,Schulz_2013_copc_hbn_moire,Iannuzzi_2014_MPc_hBN_Rh. The
trapped 2H-P molecules form isolated clusters as large as 18
molecules, which significantly differed from the observations on
hBN/Ru surface. The reduced molecule-substrate electronic coupling
refers to the hill-preferred adsorption which results in the formation
of small molecule clusters. TCNQ molecules are also found to form
individual clusters on the hBN/Cu surfaces cite:Joshi_2014_TCNQ_hBN,
suggesting the electronic nature behind such phenomenon.


*** 1D and Fractal Assembly

With increasing surface coverage or introducing directional
intermolecular interactions, 1D and fractal (with fractal
dimension between 1 and 2) assemblies may be formed on 2D material
interfaces, in the form of nanowires, nanoporous and network
structures. Note that we categorize the formation of incomplete 2D
assembly as sub-2D assembly, due to the fact that the interactions
behind these assembly forms are essentially different from the close
packing 2D assembly.

**** On strong interaction                                        :ignore:

As we discussed earlier, the strongly interacting surfaces, including
graphene/Ru(0001), graphene/Rh(111) and hBN/Ru(0001) result in the
moiré pattern that serves as specific binding sites for trapping small
molecules at low surface coverage. By increasing the surface coverage,
the specifically adsorbed molecules further act as nucleation sites
for subsequent epitaxial growth. Due to the existence of local energy
barrier, adsorption on the sites with a high energy would not be
covered until the low-energy sites are fully-occupied. The
intermolecular interactions, in combination with the geometry of moiré
pattern, result in a specific arrangement of the molecules on the
surface, varying from nanowire, nanorope to Kagome lattice. In the
case of Ref. citenum:Zhang_2011_FePc_gr, when the coverage of FePc on
Gr/Ru(0001) increases, the assembled structure changed from 0D
isolated molecules to hexagonal ring-like structure, and finally to a
Kagome lattice, at the coverage of 0.75 ML
cite:Mao_2009_Pc_gr_kagome. The top sites remain unoccupied at this
stage, in good agreement with the calculated site-specific adsorption
energy profile. Similarly, epitaxy growth of TCNQ molecules on
graphene/Ru(0001) also shows a transition from isolated clusters at
0.3 ML to Kagome lattice at 0.6 ML cite:Maccariello_2014_TCNQ_gr_Ru
(see Figure [[ref:fig-sub2D]](a)). Note that the clusters still form at a
relatively higher coverage compared to other molecules on graphene,
such as MPc, possibly due to a strong charge-transfer interaction
between TCNQ and graphene. On the other hand, increasing molecular
coverage on the strongly interacting hBN/metal surfaces didn't show
apparent formation of Kagome lattice
cite:Schulz_2013_copc_hbn_moire,Schulz_2014_hBN_moire,Iannuzzi_2014_MPc_hBN_Rh,Joshi_2014_TCNQ_hBN,
due to the different surface potential distribution compared with the
moiré pattern of graphene. Bazarnik et al. further showed that sub-ML
epitaxy of MPc molecules on graphene/Ir(111) surface is tunable by Fe-
or Co- intercalation sites below the graphene layer
cite:Bazarnik_2013_tailor_Fe_Co_gr_Ir,Avvisati_2017_FePc_intercal. For
example, the close-packed assembly of MPc molecules on weakly
interacting graphene/Ir surface completely changes to one-dimensional
chain growth, honeycomb, or Kagome lattice for CuPc and CoPc
molecules, when Fe or Co atoms were intercalated between graphene and
Ir substrate. The increased corrugation caused by intercalation atoms
was found to be the mechanism responsible for the change of epitaxial
structure. The influence of the intercalated metal atoms can be
regarded as the molecule-substrate interaction, which indirectly
affect the surface potential of the 2D material.


**** Tailoring interaction                                        :ignore:

In addition to the epitaxial behavior induced by the specific
adsorption site on 2D materials, a rich set of sub-2D assembled
structures can be obtained by tailoring the intermolecular and
molecule-substrate interactions. The concept of 2D supramolecular
self-assembly cite:De_Feyter_2003_2D_assem_rev,Philips_2D_assem_book
has been shown to be extendable under the scope of 2D materials,
yielding a broad possibility for fabricating hybrid function 2D
heterostructures. Intermolecular hydrogen bonding is widely used to
guide the orientation of surface-assisted self-assemblies
cite:Slater_2014_HBond_assembl_rev, due to its relatively high
strength. In addition, in a hydrogen-bond-bounded self-assembled
structure, the interactions perpendicular to the surface is usually
weak, thereby reducing the molecular epitaxy in the vertical
direction. Pollard et al. first studied the assembly of PTCDI
derivatives on graphene/Rh(111) surface
cite:Pollard_2010_hbond_assembly_gr. It is found that the PTCDI
molecules packed into discrete linear assemblies, distinct from those
grown on highly oriented pyrolytic graphite (HOPG) surface, in which
the PTCDI molecules form the close-packed structures. The
graphene-substrate superlattice was found to be responsible for this
phenomenon, by offering local binding sites for the PTCDI molecules,
followed by directional growth mediated by the intermolecular hydrogen
bonds. PTCDI derivatives with alkyl side chains exhibit stronger
network and Kagome-like structures, as a result of increases
side-to-side intermolecular interaction
cite:Pollard_2010_hbond_assembly_gr. Other complex supramolecular
assemblies were also found on strongly interacting graphene/metal
surface, by tailoring the molecular orientation and number of hydrogen
bonds. On graphene/Ru(0001) surface, supramolecular assembly of two
specific molecules, 2,4'-bis(terpyridine) (2,4'-BTP) and
3,3'-bis(terpyridine) (3,3'-BTP) which possess nearly identical
backbone and geometry but different pyridine substitution sites, is a
good example demonstrating the impact of the hydrogen bond orientation
on molecular assembly
cite:Meier_2010_polycyclic_gr,Roos_2011_BTP_gr,Roos_2011_hiera_org_gr
(see Figure [[ref:fig-sub2D]](b)).  The C-H \dots N hydrogen bonds formed
between 3,3'-BTP molecules were found to allow the molecules to pack
with a larger rotation angle than 2,4'-BTP. Clearly, the he minor
change in the functional group exhibited great influence on the
assembled morphology. The 3,3'-BTP molecules assembled in a curved
fashion, forming nanoropes with triangle or hexagonal shape around the
top regions of the graphene moiré pattern cite:Roos_2011_BTP_gr. On
the other hand, molecular packing of 2,4'-BTP forms linear assemblies
connecting the valley regions cite:Roos_2011_hiera_org_gr. It appears
that in this case, the strong intermolecular hydrogen bonds dominate
the molecular assembly, even on the surface with site-specific
molecule-2D material interactions. 2D growth of deposited molecules
can also be facilitated with heteromolecular hydrogen bonds. Karmel et
al. demonstrated the formation of a periodic nanoporous network by the
triple hydrogen bonds formed between PTCDI and melamine molecules on
epitaxial graphene/SiC cite:Karmel_2014_assembl_hetero_gr. On the
weakly interacting graphene/SiC surface, the triple hydrogen bonds
formed between PTCDI and melamine molecules show good lattice match,
resulting in a hexagonal nanoporous network with a lateral lattice
parameter of 3.45 nm, and each node comprised of one melamine molecule
connected three PTCDI separated by 120 $^{\deg}$. Due to a lack of
intermolecular hydrogen bonds between PTCDI molecules, the epitaxial
structure for the molecules alone show close-packed behavior
cite:Karmel_2014_PTCDI_gr. Interestingly, although the molecule-2D
material interactions are weaker than the multivalent hydrogen bonds,
the hexagonal network was found to maintain the same orientation
uniformly, indicating the weak interactions are sufficient to keep the
epitaxial layer in registry with the 2D material lattice.

In addition to hydrogen bond, several other interactions were also
found to facilitate the stabilization of sub-2D assemblies on 2D
materials. The interactions between long alkyl chains are known to
favor the formation of highly crystalline epitaxial structures
cite:De_Feyter_2003_2D_assem_rev. Molecules with long alkyl chain,
including 10,12-pentacosadiynoic acid (PCDA)
cite:Deshpande_2012_1D_assemb_gr, phosphonic acid
cite:Prado_2011_2D_acid_gr, dehydrobenzo[12]annulene (DBA) and lauroyl
peroxide cite:Huang_2016_laury_nanowire_gr were found to form ordered
nanowire to porous network structures on graphene and MoS_{2}
surfaces. The assembly of DBA molecules on graphene/SiC is shown in
Figure [[ref:fig-sub2D]](c). In these examples the close-packed long alkyl
chains were found to stabilize the structure. By proper chain length
design, herringbone cite:Deshpande_2012_1D_assemb_gr and nanoporous
network with tunable diameter cite:Li_2013_porous_assem_gr were
reported. Covalent and metal coordination bonds were also shown for
constructing sub-2D assembly on 2D materials. Successful examples
include COF on graphene connected by boronate ester
cite:Colson_2011_2DMOF_gr,Colson_2014_2D_COF_gr and imine coupling
cite:Sun_2017_cof_gr, as well as MOF on hBN by on-surface chelation
between free porphyrin and Co cite:Urgel_2015_MOF_BN.  A variety of
examples have also shown the importance of molecule-2D material
interaction. The orientation of the nanoporous network formed in
Ref. citenum:Karmel_2014_assembl_hetero_gr,Colson_2014_2D_COF_gr was
found to be in line with the lattice of graphene. On the other hand,
the assemblies on MoS_{2} cite:Huang_2016_laury_nanowire_gr and other
polar substrates (e.g. mica, SiO_{2})
cite:Karmel_2014_assembl_hetero_gr,Deshpande_2012_1D_assemb_gr,Huang_2016_laury_nanowire_gr
lose the orientation or even fail to form ordered structure. The
above examples clearly show that the \pi-\pi interactions and
collective dispersion are critical for stabilizing the aromatic
molecules on the 2D interface, while increasing dipole and Coulombic
interactions decrease the stability of such assembly.


** 2D Assembly

In principle, under sub-ML coverage, when the diffusion of molecules on  2D
material is not limited by interfacial traps, close-packed 2D assembly
can be formed in molecular epitaxy. The molecular epitaxy with
2D assembled structures can be categorized into two classes, namely the
self-assembled small organic molecules on 2D material, and the
2D heterostructures grown by vdWE.

*** Monolayer Self-Assembly of Small Molecules

The assembly of small molecules on 2D materials with low geometric and
electronic corrugation have usually been found to form close-packed
structures. Molecular dynamics (MD) simulations is a good tool to
rationalize the role of intermolecular, molecule-2D material and
molecule-substrate interactions. Zhao et al. studied the self-assembly
of non-polar pentacene and polar PTCDA molecules on planar graphene
and hBN cite:Zhao_2015_self_assemb_gr_MD. Starting from a disordered
state with sub-ML adsorption, both pentacene and PTCDA molecules ended
up in forming an ordered 2D assembled structure, within the timescale
of 100 ns. Subsequent adsorption of molecules was found to fill the
gaps in the assembled structures within 1 ns, regardless of the
initial orientation. For non-polar pentacene, the intermolecular vdW
interactions which decreased dominate structure, while the Coulombic
interactions, on the other hand, have much less effect on the
packing. However both the Coulombic and vdW interactions were found to
play important roles in stabilizing the epitaxy structure of
PTCDA. The molecule-2D material interactions determine the orientation
of the interfacial molecules. Decreasing the pentacene-graphene
potential to half of its optimized force field value changed the
packing of pentacene molecules from the face-on to edge-on
configuration (see Figure [[ref:fig-2D-MD]]). Using a similar approach,
Mukhopadhyay et al. studied the interactions involved in the
self-assembly of various small organic molecules (including benzene
derivatives, TCNQ, pentacene, C_{60}) on top of phosphorene
cite:Mukhopadhyay_2017_cryst_BP. For non-polar molecules such as
pentacene and mesitylene, the vdW potential decreases upon assembly
while the Coulombic potential slightly increases. For polar molecules
(1,3,5-trifluorobenzene, 1,3,5-trihydroxybenzene and TCNQ), the
long-range intermolecular Coulombic interactions are more
dominant. The calculated molecule-phosphorene interaction free
energies for TCNQ (-45.4 kJ/mol) and pentacene (-28.6 kJ/mol) were
comparable to those on graphene and hBN, which explain the similar
packing behavior observed on phosphorene as compared to graphene and
hBN systems. The results indicate that the non-aromatic nature of
phosphorene does not affect the stability of epitaxial molecules in
assemblies, and therefore the experimentally observed packing
structures on phosphorene may be analog to those on graphene and
hBN. To our knowledge, the effect of underlying substrate on 2D
epitaxial assembly has not been investigated under the scope of MD
simulations. However with the recently-developed knowledge of
substrate-influenced effects in wettability of 2D materials by MD
simulations cite:shih_breakdown_2012,Hung_2015_MD_water_sub, it would
be straightforward to consider the substrate effect in further work.

Although the above findings that are based on the MD-calculated
interaction energies have not taken into account the kinetic phenomena
involved in epitaxy experiments, the formation of ordered 2D
crystalline organic films on 2D materials generally correlates well to
the theoretical framework. A general feature in the 2D epitaxy of
small molecules is that the sub-2D packing formed on the strongly
interacting 2D surfaces, as discussed in the previous sections,
changes to close-packed arrangements on a weakly interacting 2D
material surface for molecules including MPc
cite:Jarvinen_2013_assembl_SiO2_hBN,Hamalainen_2012_CoPc_gr_Ir,Singha_Roy_2012_CuPc_gr_glass,Xiao_2013_jacs_CuPc_gr,Wu_2013_CuPc_F16_gr,Wang_2010_selec_F16_gr,
TCNQ cite:Barja_2010_TCNQ_gr, C_{60}
cite:Jung_2014_C60_gr_Cu,Kim_2015_c60_gr,Chen_2016_c60_mos2. The
comparisons between the epitaxial behavior on the strongly and weakly
interacting 2D material substrate have been addressed, such as FePc on
graphene/Ru(0001) and graphene/Pt(111) cite:Yang_2012_MPc_gr_metal,
TCNQ on graphene/Ru(0001) cite:Maccariello_2014_TCNQ_gr_Ru and
graphene/Ir(111) cite:Barja_2010_TCNQ_gr, CoPc on graphene/Ru(0001)
cite:Cai_2015_CoPc_gr_Ru and graphene/Ir(111)
cite:Hamalainen_2012_CoPc_gr_Ir, F_{4}-TCNQ on graphene/Ru(0001)
cite:Stradi_2014_TCNQ_gr_Ru and graphene/hBN
cite:Tsai_2015_TCNQ_gr_hbn, as shown in Figure
[[ref:fig-2D-strong-weak]].

Due to a low surface corrugation for 2D materials on the weakly
interacting surfaces, more freedom for surface adsorption and
diffusion of the small molecule is observed, resulting in the
close-packed structures. Note that a strongly interacting 2D material
does not always lead to sub-2D packing, as the molecular geometry and
intermolecular interactions also come into play. Such phenomena has
been observed in the systems of PTCDA molecules epitaxially grown on
graphene
cite:Wang_2009_STM_PTCDA_Gr,Lauffer_2008_PTCDA_gr_sic,Emery_2011_PTCDA_gr,Tian_2010_PTCDA_gr. Due
to the existence of intermolecular C-H \dots O hydrogen bonds, the
moiré pattern of graphene/Ru(0001) surface is not sufficiently strong
to trap individual PTCDA molecules cite:Wang_2009_STM_PTCDA_Gr, and
therefore a close-packed 2D assembly forms, similar to that found on
weakly interacting graphene/SiC surface
cite:Lauffer_2008_PTCDA_gr_sic,Emery_2011_PTCDA_gr. The hydrogen bond
energy per unit PTCDA herringbone lattice (400 ~ 600 meV)
cite:Tian_2010_PTCDA_gr was found to be comparable with the adsorption
energy on the top sites of the moiré pattern (~700 meV)
cite:Roos_2011_BTP_gr, revealing a competition between the
intermolecular and molecule-2D interactions. Therefore, there is a
small degree of morphological change by changing the weak interacting
substrate to the strongly-interacting substrate, as vacancies are be
found in the 2D PTCDA deposited on graphene/Ru(0001) located on the
top sites. The close-packed assemblies on the strongly interacting 2D
surface are also be found in other molecules including pentacene
cite:Zhou_2013_pent_gr_Ru and C_{60}
cite:Lu_2012_c60_gr_moire,Li_2012_c60_gr_Ru, in which the potential
barrier on the surface was overcome by kinetic energy. On the other
hand, the influence of molecule-substrate interaction has been
demonstrated in the systems of CoPc deposited on graphene/SiO_{2} and
graphene/hBN cite:Jarvinen_2013_assembl_SiO2_hBN. Specifically,
although CoPc forms cubic close-packed structures on both surfaces,
the domain size on graphene/SiO_{2} was found to be significantly
smaller than that on graphene/hBN. The LUMO energy level fluctuation
of CoPc on graphene/hBN was found to be less than that on
graphene/SiO_{2}, revealing the influence of the underlying substrate.

Following the discussions of 2D assembly, molecular packing of small
organic molecules on 2D materials other than graphene is essentially
determined by the molecule-2D material interactions, as well as the
geometry and electronic structure of the 2D material. Shen et
al. predicted the phase-dependent charge transfer between pentacene
and MoS_{2} monolayer cite:Shen_2017_DFT_mos2_pent, as briefly
mentioned in Section 2.2. A considerable degree of charge
transfer between pentacene and 1T MoS_{2} (i.e. enhanced molecule-2D
material interactions) may lead to unprecedented 2D self-assembly. The
dipole MoS_{2} surface has shown to orient the butyl-substituted PTCDI
derivative (PTCDI-C_{4}) differently from the graphene surface
cite:Arramel_2017_Ptcdi_mos2. X-ray photoelectron spectroscopy (XPS),
NEXAFS and resonant photoemission spectroscopy (RPES) where used to
reveal the edge-on orientation of PTCDI-C_{4}, compared with the
normally found face-on configuration of PTCDI compounds on graphene
cite:Karmel_2014_PTCDI_gr. The molecule-MoS_{2} interactions have been
found to be weaker than that between the alkyl chains, leading to a
tilted packing configuration. Another example is the
dioctylbenzothienobenzothiophene (C8-BTBT) epitaxy on MoS_{2}
cite:He_2015_C8BTBT_MoS2, compared with that on graphene
cite:He_2014_C8BTBT_gr. The ML thickness of C8-BTBT on MoS_{2} was
found to be ~1.2 nm, significantly larger than that on graphene (~0.7
nm), because the interfacial C8-BTBT molecules are with the "edge-on"
orientation on MoS_{2}. Clearly, the reduced vdW molecular-2D material
interaction is responsible for the substrate-dependent packing
configuration. Due to the fact that monolayer molecular assembly on 2D
materials other than graphene and hBN has not been well studied by
STM, more detailed studies will be required to uncover the molecule-2D
interaction on these 2D materials.

*** 2D van der Waals Heterostructures

We refer the 2D vdW heterostructures to the epitaxial assembled of
covalently bonded 2D materials. Chemical vapor deposition (CVD) and
van der Waals epitaxy (vdWE) are the two major methods to grow the 2D
vdW heterostructures cite:Novoselov_2016_vdW. In the view point of
molecular interactions at the interface, these two methods are
essentially similar. Therefore here we do not specify the preparation
method for the 2D vdW heterostructure in this review. The use of vdWE
for both small molecule
cite:Hara_1989_cupc_mos2_vdwe,Sakurai_1991_c60_mos2 and layered
materials
cite:Koma_1985_vdWE,Ueno_1990_vdWE,Ohuchi_1990_MoSe2_SnS2,Parkinson_1991_vdWE
on layered TMDCs has been demonstrated long before the first discovery
of graphene. The benefit of vdWE over conventional heteroepitaxy is
less constraint in lattice mismatch. In conventional heteroepitaxy,
dangling bonds exist on the substrate surface, thereby limiting the
growth of lattice-mismatch overlayer. On the other hand for 2D
materials, the interactions perpendicular to the 2D plane are mainly
vdW or Coulombic interaction, so that the overlaying 2D material can
be grown with less constraint in lattice mismatch. Figure
[[ref:fig-2D-vdW]](a) schematically shows the principle of van der Waals
epitaxy process.  As introduced in the section of intermolecular
covalent bond, a large variety of 2D vdW heterostructures have been
synthesized by vdWE approach. In this section we discuss the interplay
between the covalent bond and inter-layer interactions in the vdWE
growth of 2D vdW heterostructures.

Graphene, hBN and TMDC (in particular MoS_{2}) are the most-studied 2D
materials for vdWE growth of 2D heterostructures, due to their large
area accessibility. Epitaxial graphene cite:Yang_2013_gr_hBN, MoS_{2}
cite:Yan_2015_MoS2_on_hBN,Wang_2015_cvd_MoS2_BN and WS_{2}
cite:Cattelan_2015_Ws2_hBN have been grown by vdWE on multilayer
hBN. The epitaxial graphene on hBN was grown by plasma-enhanced CVD at
~500 $^{\circ} \mathrm{C}$, which is much lower than that required for
metal-catalyzed CVD growth of graphene (~1000 $^{\circ} \mathrm{C}$)
cite:Yang_2013_gr_hBN.  The orientation of epitaxial graphene was
found to be uniform on hBN, as revealed by the moiré pattern formation
in STM (see Figure [[ref:fig-2D-vdW]](b)). Similar to the previous
discussion about the 2D assembly of organic molecules, the interlayer
interaction is also shown to govern the stacking of 2D
heterostructure. On epitaxial or CVD-grown graphene, the vdWE
technique has been used to grow hBN cite:Lin_2014_vdW_solid, MoS_{2}
cite:Shi_2012_vdw_epi_MoS2_gr,Lin_2014_vdW_solid,McCreary_2014_MoS2_gr,Azizi_2015_Freevdw_Gr_TMDCs,Miwa_2015_MoS2_gr,Ago_2015_MoS2_Gr,
WS_{2} cite:Azizi_2015_Freevdw_Gr_TMDCs, WSe_{2}
cite:Lin_2014_WS2_Gr,Lin_2015_Wse2_MoS2_gr, and non-layered
Pb_{1-x}Sn_{x}Se cite:Wang_2015_vdw_non_layer. Monolayer epitaxial
MoS_{2} was successfully grown following on graphene, whereas the
growth on bulk SiC surface remains negligible, following the principle
of vdWE cite:Lin_2014_vdW_solid. Monolayer TMDCs were also used for
vdWE of TMDC/TMDC hybrid heterostructure, including MoTe_{2}/MoS_{2}
cite:Diaz_2015_MoTe2_MoSe2, WS_{2}/MoS_{2} cite:Gong_2014_WS2_MoS2,
GaSe/MoSe_{2} cite:Li_2016_GaSe_MoSe2_vdW (see Figure
[[ref:fig-2D-vdW]](c)), MoS_{2}/SnS_{2}
cite:Zhang_2014_vdw_epi_SnS2_MoS2. More complex vdW heterostructures
can also be synthesized using the vdWE approach. Lin et al. used
repeated vdWE on epitaxial graphene at different temperatures for the
synthesis of MoS_{2}/WSe_{2}/graphene and WS_{2}/MoSe_{2}/graphene
heterostructures cite:Lin_2015_Wse2_MoS2_gr. Alemayehu et
al. synthesized ordered stacks of GeSe_{2}/VSe_{2} heterostructures
cite:Alemayehu_2015_TMDC_vdw with controlled GeSe_{2}
layer number modulation by tuning the nucleation process.

One challenge in the vdWE growth of 2D vdW heterostructures is the
controlled growth of monolayer 2D overlayer. We note that in many 2D
heterostructures systems (mainly TMDC/graphene or TMDC/hBN) grown by
vdWE, the growth of mono- and multi- overlayers have both been
reported, including MoS_{2}/graphene
cite:Shi_2012_vdw_epi_MoS2_gr,Lin_2014_vdW_solid,Azizi_2015_Freevdw_Gr_TMDCs,Miwa_2015_MoS2_gr,Liu_2016_epi_MoS2_gr_rotation,McCreary_2014_MoS2_gr,
WSe_{2}/graphene cite:Lin_2014_vdW_solid,Azizi_2015_Freevdw_Gr_TMDCs
and MoS_{2}/hBN cite:Yan_2015_MoS2_on_hBN. The stacking sequence seems
also relevant to the layer number of the epitaxial layers. For example
almost all hBN/graphene heterostructures reported showed multilayer
hBN growth cite:Wu_2015_Gr_hBN,Lin_2014_vdW_solid, while graphene
grown on hBN tend to be monolayer
cite:Yang_2013_gr_hBN,Wu_2015_Gr_hBN. These results reveal the
importance of chemical kinetics in the vdWE heterostructure growth, since
the interplay between the interactions alone cannot explain the
discrepancy. The proposed mechanisms include
preferred nucleation sites cite:Yan_2015_MoS2_on_hBN, non-epitaxial
growth cite:Azizi_2015_Freevdw_Gr_TMDCs and synthesis method
cite:Azizi_2015_Freevdw_Gr_TMDCs. Further studies are required to
elucidate the mechanism underlying the layer-controlled growth.



** 3D Assembly

3D assembly on 2D material can be made by layer-by-layer deposition of
small molecules or epitaxy of covalently bonded structure. When the
thickness of 3D assembly increases, the intermolecular (or
interatomic) interactions become dominant over the molecule-2D
material and molecule-substrate interactions. However, this does not
mean the interfacial interactions are negligible. In fact, as will be
discussed later, the interfacial layer plays an important role in
determining the molecular orientation and morphology in the 3D
assembled structures. 3D epitaxy on 2D material interfaces may result
in various forms of nanostructures other than simple stacked
layers. The morphology of the 3D assembly greatly influence several
key properties in organic semiconductors, including carrier transport,
interfacial barrier, which motivates understanding of the underlying
mechanism.  The diversity of 3D epitaxy morphology addresses the
question of how the macroscopic structure is influenced by the
interplay between the interactions. In this section, we review the
interactions involved in a variety of 3D epitaxial structures, with
more focus on the theoretical work in this field.

*** Layer-by-Layer Assembly of Small Molecules

Layer-by-layer (LbL) self-assembly of small molecules can be viewed as
the vertical epitaxy of 2D assembled structure. The molecular
orientation and packing of the interfacial layers, i.e., the first few
layers of the molecules, are strongly influenced by the molecule-2D
material and molecule-substrate interactions, compared to the
molecules far from the interface.  The maximum molecule layer number
influenced by the 2D material and substrate highly depends on the
choice of molecule. The transition of orientation is a consequence of
the competence between the interfacial and the bulk packing
orientations. In the case of C_{60} on corrugated graphene/Ru(0001)
surface cite:Lu_2012_c60_gr_moire, the first layer of C_{60} forms
isolated single molecules trapped in the HCP valley of the moiré
pattern, which also serves as the nucleation sites for the second
layer. The second layer C_{60} molecules pack in a hexagonal pattern
around the trapped C60 molecules, namely the corrugation-guided
packing. From the third layer on, subsequent packing of C_{60}
molecules experience from dendritic to compact growth; in other words,
the influence of graphene corrugation does not go beyond the third
layer (Figure [[ref:fig-3D-layer-dep]](a)). Similarly, TCNQ assembly on
graphene/Ru(0001) also show transition from sub-2D Kagome packing to
bulk phase close-packed order when coverage is slight higher than 1ML
cite:Maccariello_2014_TCNQ_gr_Ru.  On the other hand, the second layer
CoPc molecules adsorbed on hBN/Ir(111) still prefer to occupy the pore
regions of hBN moiré pattern which have already been covered by the
first layer CoPc molecules cite:Schulz_2013_copc_hbn_moire. Multilayer
assembly of pentacene molecules on graphene is another interesting
example of layer-dependent molecule-2D material interactions. On
epitaxial graphene/SiC surface, the first layer of pentacene shows the
face-on orientation, with long-range ordering
cite:Jung_2014_pentacene. The second pentacene layer shows a tiled
angle with respect to the graphene plane, corresponding to partial
turn-over of the pentacene molecules
cite:Chen_2008_transition_pentacene. After the fifth layer, the
pentacene molecules pack in an edge-on manner, consistent with that in
the bulk pentacene film cite:Ruiz_2004_bulk_pentacene (Figure
[[ref:fig-3D-layer-dep]](b)). By increasing pentacene-graphene
interactions, a strained polymorph of pentacene was observed
cite:Kim_2015_pentacene_gr_strain, stabilizing the epitaxial structure
with consistent face-on orientation throughout the entire
film. C8-TBTB is another example that exhibits a structural
transition during epitaxial assembly. The first layer of C8-TBTB
molecules packs with the polycyclic TBTB group in contact with
graphene, forming long-range ordered linear structure
cite:He_2014_C8BTBT_gr, as a result of the \pi-\pi interactions
between TBTB core and graphene, together with the alignment of the
alkyl chains. In the bulk phase, the C8-TBTB molecules assemble with
the edge-on orientation and form cubic lattice. The transition of
orientation is found exclusively at the second layer, as revealed by the
average layer thickness change (Figure [[ref:fig-3D-layer-dep]](c)). The
observation slightly changes for C8-TBTB deposited on single layer
MoS_{2} cite:He_2015_C8BTBT_MoS2 (Figure [[ref:fig-3D-layer-dep]](d)). Due
to a weaker molecule-2D material interaction, the first layer
of C8-TBTB already shows an intermediate degree of tilted orientation between the
face-on and edge-on configurations. From second layer on, the C8-TBTB
molecules completely become the bulk phase packing.

For molecules with a large planar structure such as CuPc and
F_{16}CuPc, the strong intermolecular interactions tend to pack the
molecules along their c-axis
cite:Ren_2011_DFT_CuPc_epi_gr,Jiang_2014_F16Pc,Yoon_2010_crystal_F16cuPc. Due
to the fact that MPc molecules also take face-on orientation on
graphene surface
cite:Xiao_2013_jacs_CuPc_gr,Mativetsky_2014_CuPc_gr,Zhong_2012_gr_F16_pn_junc,
the face-on orientation can be maintained after the second layer and
continue in its 3D epitaxy structure. On the other hand, the MPc
molecules prefer to form the edge-on orientation on amorphous polar
surface such as SiO_{2} and glass
cite:Singha_Roy_2012_CuPc_gr_glass,Xiao_2013_jacs_CuPc_gr,de_Oteyza_2006_F16CuPc_sio2. As
a result, molecular orientation of epitaxial CuPc and F_{16}CuPc is be
templated by the graphene layer, screening the interactions from the
SiO_{2} or glass substrates. The idea of graphene-templated growth is
also applied to the epitaxy of pentacene cite:Lee_2011_pentacene,
perfluoropentacene cite:Salzmann_2012_fpen_gr, C_{60}
cite:Kim_2015_c60_gr and DBTTC cite:Kim_2016_DBTTC_gr. On the
contrary, the epitaxy structure of thin-layer CuPc on MoS_{2}
cite:Zhang_2015_CuPc_MoS2 shows less stability which undergo a face-on
to edge-on transition upon air exposure and forming 1D-ordered
structures. The face-on orientation, however, can be maintained at
higher deposition temperature to create a
compact structure and high turn-over barrier.

The morphology of the grown 3D epitaxial film is a consequence of both
thermodynamic and kinetic effects cite:Kowarik_2008_rev_MBE. Classical
theory of thin film organic molecular epitaxy identifies three typical
growth mechanisms, depending on their morphology, as follows: (i)
Volmer-Weber (VW) type, where the assemblies are majorly island-like,
(ii) Fran-van der Merwe (FM) type, where flat epitaxial layers are
formed, and (iii) Stranski-Krastanov (SK) type, where island formation
follows flat interfacial layer. The macroscopic phenomenon of
morphology can be explained by the interplay of surface energies of
different interfaces, including the 2D material surface
$\gamma_{\mathrm{2D}}$, surface of epitaxial molecules
$\gamma_{\mathrm{M}}$, and molecule-2D interface
$\gamma_{\mathrm{M-2D}}$, under the scope of 2D-interfacial
epitaxy. In VW type growth, it's usually observed that
$\gamma_{\mathrm{M}} + \gamma_{\mathrm{M-2D}} > \gamma_{\mathrm{2D}}$,
indicating a non-wetting of molecules at the interface, while in the
FM type growth, $\gamma_{\mathrm{M}} + \gamma_{\mathrm{M-2D}} <
\gamma_{\mathrm{2D}}$, corresponding to wetting of the molecules. The
different models of thin film growth is shown in Figure
[[ref:fig-morphology]](a). Since the surface energy is a macroscopic
property related to the intermolecular and interfacial interactions,
the growth models can also be rationalized by the interplay between
the interactions. In VW-type growth, the intermolecular interaction is
usually stronger than the molecule-2D and molecule-substrate
interactions, as the molecules tend to grow on nuclei and form
islands, while in FM- and SK- type growth, the strong interfacial
interactions lead to the formation of interfacial wetting layer. After
the first few layers, the kinetic parameters, in particular the
surface diffusivity of epitaxial molecules, play a crucial role
cite:Chatraphorn_2001_limit_diff.

The morphological control of 3D molecular epitaxy is also studied by
fine-tuning the chemical structure of epitaxial molecules, such as the
cases of CuPc/F_{16}CuPc, and pentacene/perfluoropentacene. Several
reports have indicated that the fluorination has great impact on the
assembly morphology. On graphene surface, both CuPc
cite:Singha_Roy_2012_CuPc_gr_glass,Xiao_2013_jacs_CuPc_gr and
F_{16}CuPc cite:Zhong_2012_gr_F16_pn_junc molecules form the face-on
orientation, as indicated by X-ray diffraction (XRD) and grazing
incidence X-ray diffraction (GIXD) spectroscopy. For the following
layers of both molecules, a uniform diffraction peak corresponds to
the face-on orientation is observed. However the macroscopic
morphology shows different features: CuPc tends to form a dense film
on graphene, with the grain size larger than that on SiO_{2}
cite:Singha_Roy_2012_CuPc_gr_glass,Xiao_2013_jacs_CuPc_gr, F_{16}CuPc
forms vertical nanowires on PTCDA-template surface (similar to
graphene with rich \pi-electrons) cite:Yang_2011_F16CUPc_nanowire
(Figure [[ref:fig-morphology]](b)).  Pentacene and perfluoropentacene on
MoS_{2} are also shown to have different morphologies
cite:Breuer_2016_acnene_mos2. Individual close-packed islands were
formed in 30 nm-thick the pentacene/MoS_{2} film, while the deposited
film of perfluoropentacene on MoS_{2} showed much a smoother surface,
with the island size larger than 10 $\mathrm{\mu m}$, as has been
observed in the case of pentacene and perfluoropentacene deposited on
graphene or graphite cite:Salzmann_2012_fpen_gr,Breuer_2011_pent_graph
(Figure [[ref:fig-morphology]](c)). However the interfacial layer for both
molecules were found to be the face-on orientation. Indeed, the
morphology change caused by fluorination demonstrate how minor
chemical composition change of the epitaxial molecule may affect the
macroscopic behavior in 3D molecular epitaxy. While the detailed
mechanism is still not fully understood, the change of film surface
energy $\gamma_{\mathrm{M}}$ caused by the fluorine atoms may be a
possible explanation, as indicated by the different
epitaxial growth models.

Another variable to control the macroscopic morphology is the
interfacial energy $\gamma_{\mathrm{M-2D}}$, following the previous
discussion of molecular-substrate interactions. The wetting
transparency of graphene layer enables the modulation of interfacial
energy between pentacene and graphene by changing the wettability of
the underlying substrate cite:Nguyen_2015_pent_gr_wett. Although the
growth mechanism remains to be VW-type, epitaxy on a graphene-coated
hydrophobic surface shows a larger domain size, by reducing the
heterogeneous nucleation rate, since $\gamma_{\mathrm{M-2D}}$ is
small. A smaller domain size, on the other hand, has been observed on
the graphene-coated hydrophobic surface.


*** Van der Waals Epitaxy of 3D Crystals

3D vdWE on 2D material interface shares the same mechanism with the 2D
vdWE. The absence of dangling bonds at the interface enables the
growth of 3D bulk crystal with lattice mismatch. Similar to the vdWE
of 2D heterostructures, the growth of 3D vdWE structure on layered 2D
material is not a new idea. Layered TMDCs (MoTe_{2}, WSe_{2}) have
been used for the growth of 3D crystalline semiconductors like CdS and
CdTe cite:Loeher_1994_vdw_epi_CdS_MoTe,Loeher_1996_CdTe_MoWTe. In the
case of epitaxial CdTe/MoTe_{2} and CdTe/WSe_{2}, the lattice mismatch
is as high as 30% and 40%, respectively cite:Loeher_1996_CdTe_MoWTe,
showing the power of vdWE in fabricating 3D crystalline
structures. Recent examples have shown using 2D material as template
for 3D vdWE of crystalline semiconductors, include GaAs/graphene
cite:Alaskar_2015_GaAs_gr_Si_theor,Kim_2017_remote_epi_Gr,
GaN/graphene
cite:Chung_2010_GaN_ZnO_gr,Chung_2012_GaN_gr,Chung_2012_GaN_gr,Yoo_2013_GaN_gr_defect,Nepal_2013_GaN_gr,Kim_2014_direct_vdw_GaN_gr,
GaN/hBN cite:Kobayashi_2012_GaN_hBN,Makimoto_2012_InGaN_hBN, InGaN/hBN
cite:Makimoto_2012_InGaN_hBN, ZnO/graphene cite:Chung_2010_GaN_ZnO_gr
and ZnO/hBN cite:Oh_2014_ZnO_hBN. In these systems, the 2D material
not only serves as the buffer layer for vdWE, but also acts as a
transferable layer which enables separation of the 3D crystal from the
substrate to allow fabrication of semiconductor devices
cite:Makimoto_2012_InGaN_hBN,Kobayashi_2012_GaN_hBN,Kim_2014_direct_vdw_GaN_gr,Kim_2017_remote_epi_Gr.
However a general problem encountered in the 3D vdWE process is the
low density of nucleation sites and formation of smaller clusters
instead of continuous film
cite:Loeher_1994_vdw_epi_CdS_MoTe,Loeher_1996_CdTe_MoWTe,Chung_2012_GaN_gr,Kobayashi_2012_GaN_hBN.
In 2D vdWE process, the covalent bonds are confined in-plane which
enable the growth of large area 2D layer. On the contrary, in 3D vdWE
process, the 3D covalent bonds lead to comparable growth rate in all
directions, so that the crystal size highly depends on the interfacial
nucleation density. On the other hand, the growth of metal oxides
(e.g. Al_{2}O_{3}, ZnO, TiO_{2}) on graphene or hBN lead to more
uniform films
cite:Dlubak_2012_gr_sub_assist_Al2O3,Vaziri_2013_ALD_Al2O3_gr,Zhang_2014_Al2O3_ALO_Gr,Chung_2010_GaN_ZnO_gr,Oh_2014_ZnO_hBN,Zhang_2011_TiO2_gr,Kumar_2011_gr_TiO2_generator,Li_2015_TiO2_GO,
due to an increased interfacial adsorption of precursors. 2D materials
with a ZnO or AlN buffer layers have thus been used for vdWE of large
area crystalline semiconductors
cite:Chung_2010_GaN_ZnO_gr,Yoo_2013_GaN_gr_defect,Nepal_2013_GaN_gr,Kobayashi_2012_GaN_hBN. Kim
et al. showed the nucleation density of GaN on graphene can be
enhanced by the periodic step edges of epitaxial graphene/SiC surface
cite:Kim_2014_direct_vdw_GaN_gr. Large-area single crystalline film of
epitaxial GaN with high lattice ordering has been achieved, despite
the 23% lattice mismatch between graphene and GaN. For epitaxy of
metal-oxide films, the monolayer assembled organic molecules can also
be used for seeded growth of high-quality metal oxide films on 2D
materials. For instance, Alaboson et al. used single layer
close-packed PTCDA molecules adsorbed on the epitaxial graphene/SiC
for the seeding growth of Al_{2}O_{3} and HfO_{2}
cite:Alaboson_2011_PTCDA_gr_ALD. The ALD-grown high-k metal oxide
films showed smoother morphology and less current leakage compared to
those grown in identical ALD conditions without the PTCDA seeding
layer. Besides the molecule-2D material interactions, recently Kim et
al. also showed that the 3D vdWE growth can be guided by the
interaction between the epitaxial overlayer and the underlying
substrate, in the case of the homoepitaxy of III-V semiconductors
(GaAs, InP and GaP) cite:Kim_2017_remote_epi_Gr. In other words,
graphene serves as a buffer layer for 3D vdWE. Since the thickness of
graphene (~3 \AA) is smaller than the
vdW interaction distance of the bulk material (~9 \AA for GaAs), the lattice of
the underneath substrate can guide remote homoepitaxy of the
overlayer. In principle, a series of single layer 2D materials can
serve as the vdW buffer layer for such homoepitaxy, and benefit the
design and fabrication of tandem 2D-3D heterostructures.


* Engineering 2D-Interfacial Molecular Epitaxy for Applications

Molecular epitaxy on 2D materials as an emerging route for
synthesizing functional structures with mixed dimensions have
generated research interest in their applications. Extensive reviews
have been made on the applications of 2D material hybrid structures,
including 2D vdW heterostructures
cite:Novoselov_2012_roadmap,Novoselov_2016_vdW,Hong_2017_rev_interf_eng_vdw_Het,
2D-organic interfaces
cite:Hong_2013_org_gr_interface_Rev,MacLeod_2013_rev_assembly_Gr,Kim_2017_rev_gr_org_elec,Georgakilas_2012_noncoval_gr_rev,Cai_2015_doping_2D_rev,
and mixed dimension assemblies cite:Jariwala_2016_mixed_vdw_het. With
the advance of thin-film technology, it is expected that the existing
and even theoretically-proposed 2D hybrid structures can be eventually
fabricated by molecular epitaxy. The tunability of molecular epitaxy
also provides flexible control over the dimension, orientation,
packing and morphology of the resulting films, which may be difficult
to achieve with other methods. Here we do not review in details the
applications of 2D-interfacial molecular epitaxy, but rather put our
focus on how 2D material-based applications can benefit from engineering
of 2D-interfacial molecular epitaxy, in particular about the modulation of
interactions at different length scales.

** Engineering the Properties of 2D Materials

The electronic properties, including Fermi level, bandgap,
photoluminescence, and carrier mobility of 2D materials are widely
tunable by a variety of physical and chemical approaches. Molecular
epitaxy offers two potential routes to modulate 2D material
properties, including non-covalent adsorption and interlayer coupling
in 2D heterostructures. Non-covalent adsorption with molecular epitaxy
enables doping, bandgap engineering, vibration mode modulation and
magnetism control of 2D materials. Interlayer coupling of 2D
heterostructure, on the other hand, has shown to tune the bandap, spin
state, photoluminescence, interlayer stress, and interfacial carrier
transport due to the coupling of vdW interactions. Mechanism and
examples of molecular doping of 2D materials can be found in
Refs. citenum:Wehling_2008_doping,Cai_2015_doping_2D_rev,Zhang_2011_rev_pipi_gr
and the coupling-induced tuning of 2D heterostructures can be found in
Refs.  citenum:Novoselov_2016_vdW,Hong_2017_rev_interf_eng_vdw_Het.


** Interfacial Engineering

The orientation of interfacial layer has been well-known to influence
the interfacial electronic properties, such as the carrier injection
barrier cite:Oh_2015_barristor_pent_gr,Zhong_2012_gr_F16_pn_junc,
binding energy
cite:Betti_2007_orien_pentacene,Mativetsky_2014_CuPc_gr,Xiao_2013_jacs_CuPc_gr
and anisotropic charge transfer cite:Virkar_2010_org_growth. As
discussed earlier, the template effect of 2D materials offers a
feasible approach to create functional heterojunctions. As an example,
Lee et al. employed the orientation difference between pentacene
molecules on graphene and polymer to create high-resistance lateral
junctions cite:Lee_2011_pentacene. By using the pentacene/graphene as
source and drain electrode, and pentacene/polymer in the channel
region, lateral field effect transistor with high on-off current ratio
of up to $10^{8}$ was demonstrated. The highly ordered packing
behavior of molecules on 2D material templates have also been employed
for other lateral
cite:Kim_2016_trap_Mos2_pent,Jariwala_2016_Mos2_pentacene,Lee_2014_rubene_hBN
and vertical cite:Kim_2015_c60_gr,Shih_2015_PartiallyScreened field
effect transistors, photosensors cite:Bettis_Homan_2017_pentacene_Mos2
and light emitting diodes (LED)
cite:Makimoto_2012_InGaN_hBN,Kobayashi_2012_GaN_hBN,Kim_2014_direct_vdw_GaN_gr,Kim_2017_remote_epi_Gr.


** Nanostructure-Based Applications

Finally, the morphological change induced by the 2D material in
molecular epitaxial may enable new approaches to tailor the physical
properties of the 2D complexes, especially when hierarchical or high
aspect-ratio nanostructures are formed. For example, Wang et al. used
graphene as template to grow highly-ordered vertical arrays of
oligoaniline cite:Wang_2015_vertical_nanowire_gr. The \pi-\pi
molecule-graphene interaction leads to selective modification of
graphene, which further enables patterned growth of vertical
oligoaniline arrays. The ordered packing of oligoaniline resulted in
high conductivity of 12.3 S/cm. Zheng et al. used graphene as a
template for the solution-based growth of dense array of vertical
9,10-bis(phenylethynyl) anthracene (BPEA) semiconducting nanowires
cite:Zheng_2016_vnanowire_gr. The high aspect ratio and narrowly
dispersed diameter of the nanowires enable high-performance array of
cavities with strong optical dispersion. Another example of the
nanostructures grown by molecular epitaxy using molecular epitaxy on
2D materials is the growth of nanowall-nanowire hybrid structures of
ZnO on graphene by controlling the interfacial nucleation density
cite:Kumar_2011_gr_TiO2_generator. Combining the piezoelectric effect
of ZnO, the high aspect ratio of nanowires, the specific electron dynamics
of the nanowall-nanowire interface, and the high conductance of graphene,
the hybrid structure was used as an effective nanoscale power generator.



* Summary

Molecular epitaxy on 2D materials has been proven to be a powerful
approach to create multidimensional hybrid structures. Understanding
the mechanism, in particular the interplay between the interactions
behind the complex epitaxial structures is important towards
engineering the heterostructures. In this article, we review the
interactions involved in the molecular epitaxy on 2D materials,
including the intermolecular, molecule-2D material and
molecule-substrate interactions. By looking into various examples of
the epitaxial assemblies, we discuss the influence of each interaction
on the dimension, interfacial orientation, lattice packing and
morphology of the resulting heterostructures. By increasing the
molecule-2D material and molecule-substrate interactions, the
epitaxial structure tends to be more surface-specific, and different
from that in bulk phase. It is often observed that even weak
molecule-2D material interactions can be crucial in stabilizing the
interfacial structure and its orientation. The unique surface-induced
assembled structures enable a variety of applications, including
tailoring the electronic properties of 2D materials, high performance
field effect devices and multifunctional nanostructure surfaces. Here
we highlight that there are several key issues regarding molecular
epitaxy on 2D materials that remain poorly understood, including (i)
the relationship between the electronic structure of the 2D material
and the interfacial interactions, (ii) the effective interaction range
of the underlying substrate in different 2D material systems, (iii) a
general model describing the molecule-2D material and
molecule-substrate interactions, and (iv) the governing factors for
the morphology of the resulting structure. Further theoretical and
experimental investigations are required to address the above
questions. We believe that reproducible, high throughput, and
controllable fabrication of the 2D hybrid heterostructures will be
benefited from the fundamental principles covered in this review.

#+BEGIN_EXPORT latex
\begin{acknowledgement}
The authors are grateful for the financial support from the ETH startup funding.
\end{acknowledgement}
#+END_EXPORT

* References                                                         :ignore:
[[bibliography:ref.bib]]

* Figures                                                            :ignore:

\newpage{}


#+NAME: fig-scheme-2D-mater
#+ATTR_LATEX: :float multicolumn
#+CAPTION: Structures of 2D materials. (a) graphene, (b) hBN, (c) TMDC (2H-type), (d) phosphorene. The inset of each subfigure shows the structure of the 2D material viewed from the top.
[[file:../img/scheme-2D-material.pdf]]


#+NAME: fig-scheme-interactions
#+ATTR_LATEX: :float multicolumn
#+CAPTION: Types of molecular interactions involved in the molecular epitaxy on 2D materials, categorized into intermolecular interaction of epitaxial molecules, molecule-2D material and molecule-substrate interactions. Multidimensional epitaxial structures from sub-2D to 3D assemblied are reviewed in the context of this article.
[[file:../img/scheme_interactions.pdf]]

#+NAME: fig-org-structure
#+ATTR_LATEX: :float multicolumn
#+CAPTION: Chemical structures of organic molecules frequently quoted in this review: C_{60}, MPc, TCNQ, F_{4}-TCNQ, pentacene, perfluoropentacene and PTCDA
[[file:../img/scheme-organic.pdf]]


#+NAME: fig-tune-vdW
#+ATTR_LATEX: :float multicolumn
#+CAPTION: Tunable molecule-2D interaction by doping of 2D material. (a) Tunable vdW interaction between napthlene (Nph) and graphene by substrate doping of intercalating Eu between graphene/Ir(111) (G/Ir) surface, indicated by exclusive adsorption of naphthlene (Nph) molecules on Eu intercalaterd region (G/Eu/Ir) cite:Huttmann_2015_vdw_gr_doping. (b) Tunable vdW interaction between CO_{2} and graphene by electrostatic doping. Molecular orbitals of CO_{2} on pristine and doped graphene are shown cite:Muruganathan_2015_tunable_vdw_gr. Figures adapted from Refs. citenum:Huttmann_2015_vdw_gr_doping,Muruganathan_2015_tunable_vdw_gr.
[[file:../img/tune-vdw-doping.pdf]]

#+NAME: fig-scheme-moire
#+ATTR_LATEX: :float multicolumn
#+CAPTION: Scheme of the moiré patterns formed in (a) graphene/Ru(0001), with valley (fcc, hcp) and hill (top) regions labeled and (b) hBN/Ru(0001) with pore and wire regions marked.
[[file:../img/scheme-moire-gr-hbn.pdf]]

#+NAME: fig-trans-vdW
#+ATTR_LATEX: :float multicolumn
#+CAPTION: Examples which show the penetration of vdW interaction from the substrate through 2D material. (a) Layer-dependent morphology of 6P epitaxy on graphene/SiO_{2}. The proposed morphology change is shown below cite:Kratzer_2014_6P_gr_layer. (b) Substrate hydrophobolicity-dependent epitaxial morphology of pentacene on different graphene-covered surfaces cite:Nguyen_2015_pent_gr_wett. (c) Spatial electron density of separating two GaN slabs with a certain distance from first principles calculation. At a distance <9 \AA the vdW interaction is continuous in the gap cite:Kim_2017_remote_epi_Gr. (d) Cross sectional high resolution transmission electron microscopy image of the homoepitaxial GaAs on graphene/GaAs in (c). The lattic of the epitaxy and substrate GaN shows perfect match. Figures adapted from Refs. citenum:Kratzer_2014_6P_gr_layer,Nguyen_2015_pent_gr_wett,Kim_2017_remote_epi_Gr
[[file:../img/transparency_vdW.pdf]]

#+NAME: fig-0D
#+ATTR_LATEX: :float multicolumn
#+CAPTION: STM images of 0D assemblies formed on strongly interacting 2D surfaces. (a) Isolated Ir clusters on graphene/Ir surface. Inset shows details about the adsorption on the hcp sites cite:N_Diaye_2006_Ir_gr_Ir. (b) Au 0D clusters on hBN/Ru nanomesh cite:Goriachko_2008_AuNP_moire_hBN. (c) Trapped CuPc molecules in the pore regions of hBN/Ru. Inset shows off-center adsorption in the pore for a single molecule cite:Iannuzzi_2014_MPc_hBN_Rh. (d) Trapping of single C_{60} molecule in the hcp valley of a graphene/Ru surface cite:Lu_2012_c60_gr_moire. Figures adapted from Refs citenum:N_Diaye_2006_Ir_gr_Ir,Goriachko_2008_AuNP_moire_hBN,Iannuzzi_2014_MPc_hBN_Rh,Lu_2012_c60_gr_moire.
[[file:../img/0D.pdf]]

#+NAME: fig-sub2D
#+ATTR_LATEX: :float multicolumn
#+CAPTION: Examples of sub-2D assmebly formation by various intermolecular interactions on 2D materials. (a) Transistion of 0D assembly of TNCQ on graphne/Ru at 0.3 ML coverage to Kagome lattice formation at 0.6 ML cite:Maccariello_2014_TCNQ_gr_Ru. (b) Distinct assembly of hydrongen-bonded 2,4'-BTP (left) with nanorope structure and 3,3'-BTP (right) with linear assembly, on graphene/Ru surface cite:Roos_2011_BTP_gr,Roos_2011_hiera_org_gr. (c) Kagome lattice formation of alkyl-DBA on graphene/SiC, stablized by interactions between hydrocarbon chains cite:Li_2013_porous_assem_gr. Figures adapted from Refs. citenum:Maccariello_2014_TCNQ_gr_Ru,Roos_2011_hiera_org_gr,Roos_2011_BTP_gr,Li_2013_porous_assem_gr
[[file:../img/sub2D.pdf]]

#+NAME: fig-2D-MD
#+ATTR_LATEX: :float multicolumn
#+CAPTION: Mechanism of 2D vdW assembly of pentacene on graphene by MD simulation. The ordered assembly forms simultaneously from a random assembly configuration. The influence of changing the molecule-2D, Coulombic and vdW interations are show below cite:Zhao_2015_self_assemb_gr_MD. Figure adapted from Ref. citenum:Zhao_2015_self_assemb_gr_MD.
[[file:../img/2D-MD.pdf]]

#+NAME: fig-2D-strong-weak
#+ATTR_LATEX: :float multicolumn
#+CAPTION: The influence of molecule-2D material interactions on the 2D assembly, shown by STM images of (a) FePc on graphene/Ru and graphene/Ir cite:Yang_2012_MPc_gr_metal, (b) CoPc on graphene/Ru cite:Cai_2015_CoPc_gr_Ru and graphen/Ir cite:Hamalainen_2012_CoPc_gr_Ir, and (c) F_{4}-TCNQ on graphene/Ru cite:Stradi_2014_TCNQ_gr_Ru and graphene/hBN cite:Tsai_2015_TCNQ_gr_hbn. On strongly interacting graphene surfaces the molecules pack in a sub-2D assembly while on weakly interacting surface close packing is always observed. Figures adapted from Refs. citenum:Yang_2012_MPc_gr_metal,Cai_2015_CoPc_gr_Ru,Hamalainen_2012_CoPc_gr_Ir,Stradi_2014_TCNQ_gr_Ru,Tsai_2015_TCNQ_gr_hbn.
[[file:../img/2D-strong-weak.pdf]]

#+NAME: fig-2D-vdW
#+ATTR_LATEX: :float multicolumn
#+CAPTION: Van der Waals epitaxy of 2D heterostructures. (a) The principle of vdWE process, which has less limit of lattice mismatch than conventional heteroepitaxy, for both 2D and 3D epitaxy on 2D materials. (b) Growing of single crystal graohene on hBN by plasma-enhanced CVD. Large area graphene/hBN heterostructure with ordered moiré pattern can be seen cite:Yang_2013_gr_hBN. (c) Epitaxial growth of single layer GaSe on single layer MoSe_{2} flakes cite:Li_2016_GaSe_MoSe2_vdW. Figures adapted from Refs. citenum:Yang_2013_gr_hBN,Li_2016_GaSe_MoSe2_vdW.
[[file:../img/2D-vdW.pdf]]

#+NAME: fig-3D-layer-dep
#+ATTR_LATEX: :width 0.8\linewidth :float multicolumn
#+CAPTION: The influence of interfacial interactions on layer-by-layer epitaxy stucture. (a) C_{60} deposited on graphene/Ru surface. The trapped nucleation sites influence the packing of the first two layers, while the third layer has a packing as in the bulk phase cite:Lu_2012_c60_gr_moire. (b) Layer-dependent morphology of pentacene on epitaxial graphene/SiC. The interface-induced face-on orientation is shown to be partially inherited in the second layer, while the third layer adopts the herringbone packing like in the bulk phase cite:Jung_2014_pentacene. (c) Packing of C8-TBTB on graphene cite:He_2014_C8BTBT_gr. The graphene-induced faced-on orientation propagate within the first 2 layers. (d) Packing of C8-TBTB on MoS_{2}. The MoS_{2} is found to have less orientation guiding for the C8-TBTB molecule cite:He_2015_C8BTBT_MoS2. Figures adapted fro Refs. citenum:Lu_2012_c60_gr_moire,Jung_2014_pentacene,He_2014_C8BTBT_gr,He_2015_C8BTBT_MoS2.
[[file:../img/layer-dependent.pdf]]

#+NAME: fig-morphology
#+ATTR_LATEX: :width 0.75\linewidth :float multicolumn
#+CAPTION: Macroscopic morphology of 3D molecular epitaxy. (a) The VW, FM and SK growth models. (b) The difference between the morphology of CuPc and F_{16}CuPc on graphene/PTCDA cite:Singha_Roy_2012_CuPc_gr_glass,Yang_2011_F16CUPc_nanowire. (c) The difference between the morphology of pentacene (PEN) and perfluoropentacene (PFP) on MoS_{2} cite:Breuer_2016_acnene_mos2. In both cases the orientaion of the H- and F- substituted molecule are the same. Figures adapted from Refs. citenum:Singha_Roy_2012_CuPc_gr_glass,Yang_2011_F16CUPc_nanowire,Breuer_2016_acnene_mos2.
[[file:../img/morphology.pdf]]


